"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Lang = "de" | "en";

export const t = {
  de: {
    // Sidebar
    nav_dashboard: "Dashboard",
    nav_codes: "QR Codes",
    nav_settings: "Einstellungen",
    nav_users: "Benutzer",
    nav_clients: "Kunden",
    nav_plans: "Pläne",
    nav_plan_settings: "Plan-Einstellungen",
    nav_language: "Sprache",
    plan_settings_title: "Plan-Einstellungen",
    plan_settings_subtitle: "Preise und Funktionen für jeden Plan bearbeiten.",
    plan_settings_price: "Preis (CHF/Monat)",
    plan_settings_features: "Funktionen (max. 4)",
    plan_settings_feature_placeholder: "z.B. Unbegrenzte QR Codes",
    plan_settings_save: "Speichern",
    plan_settings_saved: "Gespeichert!",
    plan_settings_edit: "Bearbeiten",
    plan_settings_cancel: "Abbrechen",
    plan_settings_stripe_warning: "⚠️ Preisänderungen werden NICHT automatisch in Stripe übernommen. Bitte den Preis auch im Stripe-Dashboard manuell aktualisieren.",
    plan_settings_stripe_confirm: "Verstanden, trotzdem speichern",
    plan_settings_stripe_title: "Stripe manuell aktualisieren",
    plan_settings_stripe_body: "Preise hier und in Stripe sind nicht verknüpft. Eine Änderung hier aktualisiert nur die Anzeige. Stripe bleibt unverändert.",
    plan_settings_stripe_steps: "Nach dem Speichern bitte in Stripe:",
    plan_settings_stripe_step1: "Neuen Preis für das Produkt erstellen",
    plan_settings_stripe_step2: "Alten Preis archivieren",
    plan_settings_stripe_step3: "Neue Preis-ID im Code hinterlegen",
    logout: "Abmelden",
    // Dashboard page
    dashboard_subtitle: "Verwalten Sie Ihre QR Codes",
    create_qr: "QR Code erstellen",
    stat_total: "Gesamt QR Codes",
    stat_active: "Aktiv",
    stat_paused: "Pausiert",
    stat_phone: "Mit Telefon",
    stat_website: "Mit Website",
    all_codes: "Alle QR Codes",
    no_codes: "Noch keine QR Codes",
    no_codes_sub: "Erstellen Sie Ihren ersten QR Code",
    create_now: "Jetzt erstellen",
    col_name: "Name / Musterfirma",
    col_created: "Erstellt",
    col_link: "Link",
    col_actions: "Aktionen",
    col_created_by: "Erstellt von",
    delete_confirm: "Nochmal klicken zum Bestätigen",
    delete: "Löschen",
    // Codes page
    new_qr: "Neuer QR Code",
    search_placeholder: "Suche nach Name, Musterfirma oder ID...",
    no_results: "Keine QR Codes gefunden",
    unnamed: "Unbenannt",
    edit: "Bearbeiten",
    codes_total: "QR Codes gesamt",
    // Settings
    settings_title: "Einstellungen",
    settings_subtitle: "Plattform-Einstellungen",
    settings_placeholder: "Einstellungen werden in einer zukünftigen Version verfügbar sein.",
    settings_account: "Konto",
    settings_plan_change: "Plan ändern",
    settings_email_change: "E-Mail ändern",
    settings_email_current: "Aktuelle E-Mail",
    settings_email_new: "Neue E-Mail-Adresse",
    settings_email_saving: "Wird gespeichert...",
    settings_email_btn: "E-Mail ändern",
    settings_email_error_same: "Bitte eine andere E-Mail-Adresse eingeben.",
    settings_email_success: "Bestätigungs-E-Mail wurde gesendet. Bitte prüfen Sie Ihr Postfach und bestätigen Sie die neue Adresse.",
    settings_pw_change: "Passwort ändern",
    settings_pw_current: "Aktuelles Passwort",
    settings_pw_new: "Neues Passwort",
    settings_pw_confirm: "Neues Passwort bestätigen",
    settings_pw_saving: "Wird gespeichert...",
    settings_pw_btn: "Passwort ändern",
    settings_pw_error_match: "Passwörter stimmen nicht überein.",
    settings_pw_error_short: "Mindestens 6 Zeichen erforderlich.",
    settings_pw_error_wrong: "Aktuelles Passwort ist falsch.",
    settings_pw_success: "Passwort erfolgreich geändert.",
    // Create page
    create_title: "Neuer QR Code",
    create_subtitle: "Füllen Sie die Felder aus und erstellen Sie Ihren QR Code",
    create_error: "Fehler beim Erstellen. Bitte versuchen Sie es erneut.",
    create_submit: "QR Code erstellen",
    // Edit page
    edit_title: "QR Code bearbeiten",
    edit_success: "QR Code erfolgreich erstellt!",
    saved: "Gespeichert!",
    save_error: "Fehler beim Speichern.",
    open_page: "Seite öffnen",
    copy_link: "Link kopieren",
    copied: "Kopiert!",
    download_qr: "QR herunterladen",
    save: "Speichern",
    // QRForm
    qr_label: "QR Code Name",
    qr_label_hint: "Nur für Sie sichtbar – hilft beim Erkennen im Dashboard.",
    qr_label_placeholder: "z.B. Messe 2026, Visitenkarte Büro",
    section_identity: "Angaben",
    section_contact: "Kontaktdaten",
    section_social: "Social Media",
    section_pdf: "Dateien / PDF",
    section_notes: "Notizen (intern)",
    field_first_name: "Vorname",
    field_last_name: "Name",
    field_title: "Titel / Position",
    field_company: "Musterfirma",
    field_logo: "Logo / Profilbild",
    field_logo_hint: "Direkter Bildlink (PNG, JPG, SVG)",
    upload_remove: "Entfernen",
    upload_uploading: "Wird hochgeladen…",
    upload_error_size: "Dateien zu groß. Maximum 14 MB.",
    upload_error_failed: "Upload fehlgeschlagen. Bitte erneut versuchen.",
    upload_logo: "Logo hochladen",
    upload_logo_hint: "Max. 14 MB · Wird automatisch komprimiert wenn nötig",
    upload_pdf: "PDF hochladen",
    upload_pdf_open: "Aktuelle Dateien öffnen",
    upload_pdf_hint: "Max. 14 MB · Nur PDF-Dateien",
    pdf_option_upload: "Dateien hochladen",
    pdf_option_link: "Link hinzufügen",
    link_label_placeholder: "z.B. Broschüre, Preisliste…",
    link_add: "Hinzufügen",
    links_max: "Maximum 4 Einträge erreicht",
    field_color: "Akzentfarbe",
    field_color_hint: "Wird als Hintergrundfarbe auf Ihrer QR-Visitenkarte verwendet.",
    upload_bg: "Hintergrundbild hochladen",
    upload_bg_hint: "Max. 14 MB · Wenn leer, wird die Akzentfarbe verwendet.",
    field_phone: "Telefon",
    field_email: "E-Mail",
    field_website: "Webseite",
    field_street: "Strasse",
    field_street_nr: "Nr.",
    field_plz: "PLZ",
    field_city: "Ort",
    field_linkedin: "LinkedIn URL",
    field_instagram: "Instagram URL",
    field_facebook: "Facebook URL",
    field_tiktok: "TikTok URL",
    field_snapchat: "Snapchat URL",
    field_x: "X (Twitter) URL",
    field_other_social: "Andere (URL)",
    field_pdf_url: "PDF / Datei URL",
    field_pdf_label: "Button-Beschriftung",
    field_notes: "Interne Notiz",
    field_notes_placeholder: "Nur im Dashboard sichtbar...",
    cancel: "Abbrechen",
    // Plan
    plan_label: "Plan",
    plan_limit_reached: "Limit erreicht für Plan",
    plan_upgrade_hint: "Bitte upgraden Sie Ihren Plan.",
    free_plan_banner: "Du nutzt den kostenlosen Plan – nur 1 QR Code möglich.",
    free_plan_upgrade: "Jetzt upgraden →",
    plan_limit_ask_owner: "Bitte den Account-Inhaber, den Plan zu upgraden",
    see_plans: "Pläne ansehen",
    // Upgrade page
    upgrade_title: "Plan upgraden",
    upgrade_subtitle: "Wählen Sie den passenden Plan für Ihre Bedürfnisse",
    upgrade_current: "Aktuell",
    upgrade_per_month: "/Monat",
    upgrade_current_plan: "Ihr aktueller Plan",
    upgrade_loading: "Wird geladen…",
    upgrade_select: "wählen",
    upgrade_no_expiry: "Kein Ablauf",
    upgrade_unlimited: "Unbegrenzt",
    // Social placeholders
    social_placeholder: "Benutzername",
    qr_logo_in_center: "Logo im QR Code anzeigen",
    delete_modal_title: "QR Code löschen?",
    delete_modal_body: "Alle Daten dieses QR Codes werden unwiderruflich gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.",
    delete_modal_cancel: "Abbrechen",
    delete_modal_confirm: "Ja, löschen",
    // Roles
    role_admin: "Admin",
    role_writer: "Bearbeiter",
    role_reader: "Leser",
    role_owner: "Owner",
    role_label: "Rolle",
    our_plans: "Unsere Pläne",
    // Users page
    users_title: "Benutzerverwaltung",
    users_subtitle: "Laden Sie Teammitglieder ein und verwalten Sie deren Rollen.",
    users_invite: "Benutzer einladen",
    users_invite_email: "E-Mail-Adresse",
    users_invite_role: "Rolle",
    users_invite_btn: "Einladen",
    users_invite_sending: "Wird gesendet…",
    users_invite_success: "Einladung gesendet!",
    users_invite_error: "Fehler beim Senden.",
    users_col_email: "E-Mail",
    users_col_role: "Rolle",
    users_col_joined: "Beigetreten",
    users_remove: "Entfernen",
    users_no_members: "Keine weiteren Mitglieder",
    users_resend: "Einladung erneut senden",
    users_resend_sending: "Wird gesendet…",
    users_resend_success: "Einladung erneut gesendet!",
    created_by: "Erstellt von",
    // Clients page
    clients_title: "Kunden",
    clients_subtitle: "Übersicht aller registrierten Kunden-Accounts.",
    clients_no_clients: "Noch keine Kunden registriert.",
    clients_col_qr: "QR Codes",
    clients_col_joined: "Registriert",
    clients_change_plan: "Plan ändern",
    clients_delete: "Konto löschen",
    clients_delete_confirm: "Wirklich löschen?",
    clients_stat_total: "Kunden gesamt",
    clients_plan_modal_title: "Plan wirklich ändern?",
    clients_plan_modal_stripe: "⚠️ Falls der Kunde ein aktives Stripe-Abo hat, wird dieses NICHT automatisch aktualisiert. Bitte Stripe manuell anpassen.",
    clients_plan_modal_confirm: "Ja, Plan ändern",
    clients_plan_modal_cancel: "Abbrechen",
    clients_inactive_title: "Inaktive Kunden",
    clients_inactive_body: "Diese Kunden haben in den letzten 1 Tag(en) keine QR Codes erstellt oder bearbeitet.",
    clients_last_active: "Zuletzt aktiv",
    clients_never_active: "Noch keine Aktivität",
    clients_view: "Anzeigen",
    // Client detail page
    client_detail_back: "Zurück zu Kunden",
    client_detail_profile: "Profil",
    client_detail_members: "Team-Mitglieder",
    client_detail_qrcodes: "QR Codes",
    client_detail_total_scans: "Scans gesamt",
    client_detail_joined: "Registriert",
    client_detail_last_active: "Letzte Aktivität",
    client_detail_stripe: "Stripe",
    client_detail_no_members: "Keine Team-Mitglieder",
    client_detail_no_qr: "Noch keine QR Codes",
    client_detail_active: "Aktiv",
    client_detail_paused: "Pausiert",
    client_detail_scans: "Scans",
    client_detail_role: "Rolle",
    client_detail_joined_team: "Beigetreten",
    // Paused QR page
    qr_paused_title: "QR Code pausiert",
    qr_paused_body: "Dieser QR Code ist derzeit pausiert. Der Inhaber muss seinen Plan upgraden, um ihn zu reaktivieren.",
    // Onboarding
    onboarding_title: "Willkommen! 👋",
    onboarding_subtitle: "In 3 einfachen Schritten loslegen:",
    onboarding_step1: "Erstellen Sie Ihren ersten QR Code",
    onboarding_step2: "Teilen Sie den Link oder drucken Sie den QR Code",
    onboarding_step3: "Bearbeiten Sie Ihre Daten jederzeit. Der QR Code bleibt gleich.",
    onboarding_dismiss: "Verstanden, loslegen!",
    // Scan analytics
    scans_total: "Scans gesamt",
    scans_label: "Scans",
    scans_today: "Heute",
    scans_last7: "Letzte 7 Tage",
    field_description: "Beschreibung",
    // Theme
    field_theme: "Karten-Design",
    theme_classic: "Classic",
    theme_dark: "Dark",
    theme_minimal: "Minimal",
    // Codes filter
    filter_all: "Alle",
    filter_active: "Aktiv",
    filter_paused: "Pausiert",
    qr_paused_badge: "Pausiert. Plan upgraden zum Reaktivieren.",
    sort_newest: "Neueste zuerst",
    sort_oldest: "Älteste zuerst",
    sort_name: "Name A–Z",
    export_csv: "CSV exportieren",
    contact_support: "Support kontaktieren",
    settings_support_email_title: "Kontakt-E-Mail",
    settings_support_email_hint: "Wird Team-Mitgliedern bei Fehlern angezeigt.",
    settings_support_email_btn: "Speichern",
    // Landing page
    landing_call: "Anrufen",
    landing_email_default: "E-Mail",
    landing_website_default: "Webseite",
    landing_document: "Dokument",
    landing_link: "Link",
    landing_save_contact: "Kontakt speichern",
    landing_share: "Teilen",
    landing_copied: "Kopiert!",
    landing_lead_btn: "Kontakt hinterlassen",
    landing_lead_title: "Kontakt hinterlassen",
    landing_lead_subtitle_suffix: "wird sich bei Ihnen melden.",
    landing_lead_thanks: "Vielen Dank!",
    landing_lead_received: "Ihre Kontaktdaten wurden empfangen.",
    landing_lead_close: "Schliessen",
    landing_lead_name: "Name",
    landing_lead_email: "E-Mail",
    landing_lead_comment: "Nachricht",
    landing_lead_optional: "(optional)",
    landing_lead_name_ph: "Ihr vollständiger Name",
    landing_lead_email_ph: "ihre@email.com",
    landing_lead_comment_ph: "Nachricht oder Notiz…",
    landing_lead_consent: "Ich willige ein, dass mein Name, E-Mail und meine Nachricht gespeichert und zur Kontaktaufnahme verwendet werden dürfen. Ich kann meine Einwilligung jederzeit widerrufen.",
    landing_lead_consent_required: "Bitte stimmen Sie der Datenverarbeitung zu, um fortzufahren.",
    landing_lead_sending: "Wird gesendet…",
    landing_lead_send: "Senden",
    landing_lead_error_generic: "Etwas ist schiefgelaufen.",
    landing_lead_error_network: "Netzwerkfehler. Bitte erneut versuchen.",
    // Dashboard page
    dashboard_title: "Dashboard",
    kpi_total_qrs: "QR Codes gesamt",
    kpi_total_scans: "Scans gesamt",
    kpi_unique_visitors: "Eindeutige Besucher",
    kpi_returning: "Wiederkehrend",
    kpi_conversion_rate: "Conversion Rate",
    dashboard_active_codes: "Aktive QR Codes",
    dashboard_paused_codes: "Pausierte QR Codes",
    chart_title: "Scans im Zeitverlauf",
    chart_subtitle: "Gesamte Scans aller QR Codes",
    chart_no_scans: "Keine Scans in diesem Zeitraum",
    recent_codes: "Neueste QR Codes",
    view_all: "Alle anzeigen",
    no_qrs_yet: "Noch keine QR Codes",
    create_first: "Ersten erstellen",
    by_label: "Von",
    interactions_title: "Interaktionen",
    interactions_subtitle: "Klick-Anzahl über alle QR Codes",
    interactions_total: "gesamt",
    no_interactions: "Noch keine Interaktionen erfasst",
    top_qrs_title: "Top QR Codes",
    top_qrs_subtitle: "Sortiert nach Scan-Anzahl",
    no_scan_data: "Noch keine Scan-Daten",
    upgrade_plan_btn: "Plan upgraden →",
    evt_phone: "Telefon",
    evt_email: "E-Mail",
    evt_website: "Webseite",
    evt_pdf: "PDF",
    evt_link: "Link",
    evt_save_contact: "Kontakt speichern",
    evt_share: "Teilen",
    evt_linkedin: "LinkedIn",
    evt_instagram: "Instagram",
    evt_facebook: "Facebook",
    evt_tiktok: "TikTok",
    evt_snapchat: "Snapchat",
    evt_x: "X",
    evt_other: "Sonstige",
    evt_lead_open: "Lead-Formular geöffnet",
    evt_lead_submit: "Lead gesendet",
    // Edit page
    edit_qr_ready: "Ihr QR Code ist bereit. Laden Sie ihn unten herunter oder passen Sie ihn an und speichern.",
    edit_basic_info: "Basisinformationen",
    edit_dest_folder: "Zielordner",
    optional: "(optional)",
    // Settings page (additional)
    settings_subtitle_full: "Verwalten Sie Ihr Konto und globale Plattformeinstellungen.",
    settings_account_info: "Kontoinformationen",
    settings_full_name: "Vollständiger Name",
    settings_email_label: "E-Mail-Adresse",
    settings_role_label: "Rolle:",
    settings_plan_change_short: "Ändern",
    settings_security: "Sicherheit",
    settings_2fa: "Zwei-Faktor-Authentifizierung",
    settings_2fa_hint: "Zusätzliche Login-Sicherheit über Authenticator-App",
    settings_2fa_disabled: "Vom Admin deaktiviert",
    settings_pw_confirm_label: "Passwort bestätigen",
    // Upgrade page
    upgrade_subscription_mgmt: "Abonnement-Verwaltung",
    upgrade_active_btn: "Aktiv",
    upgrade_stay_free: "Beim Free Plan bleiben",
    upgrade_compare_features: "Funktionen vergleichen",
    upgrade_core_feature: "Kernfunktion",
    upgrade_plan_free: "Free",
    upgrade_plan_star: "Star",
    upgrade_plan_premium: "Premium",
    // Leads
    leads_title: "Leads",
    leads_subtitle: "Kontakte, die über Ihre QR-Karten eingereicht wurden",
    leads_search_ph: "Suche nach Name, E-Mail oder QR-Karte…",
    leads_all_members: "Alle Mitglieder",
    leads_none_search: "Keine Leads für diese Suche",
    leads_none: "Noch keine Leads",
    leads_none_hint: "Aktivieren Sie Lead Capture auf einer QR-Karte, um Kontakte zu sammeln.",
    leads_count_one: "Lead",
    leads_count_many: "Leads",
    leads_open_live: "Live-Karte öffnen",
    leads_edit: "Bearbeiten",
    leads_analytics: "Analyse",
    leads_preview_qr: "QR Code Vorschau",
    leads_edit_card: "QR-Karte bearbeiten",
    leads_qr_card: "QR Karte",
    // NFC
    nfc_title: "NFC Karten",
    nfc_subtitle: "Physische NFC-Karten registrieren und Profilen zuweisen",
    nfc_register: "NFC Karte registrieren",
    nfc_register_hint: "Geben Sie die eindeutige ID ein, die auf der Karte gedruckt oder gespeichert ist",
    nfc_card_uid: "Karten-UID / Code *",
    nfc_label_optional: "Beschriftung (optional)",
    nfc_assign_profile: "Profil zuweisen (optional)",
    nfc_no_cards: "Keine NFC Karten registriert",
    nfc_no_cards_hint: "Registrieren Sie Ihre erste NFC Karte und weisen Sie sie einem Profil zu",
    nfc_no_contacts: "Keine Kontakte gefunden",
    nfc_save: "Speichern",
    nfc_cancel: "Abbrechen",
    nfc_not_assigned: "Nicht zugewiesen",
    // Folders
    folders_title: "Ordner",
    folders_total_suffix: "Ordner insgesamt",
    folders_load_error: "Fehler beim Laden",
    folders_name_ph: "Ordnername",
    folders_save: "Speichern",
    folders_create: "Erstellen",
    folders_move: "Ordner verschieben",
    folders_move_for: "Neues Verzeichnis für",
    folders_root_option: "— Root (kein übergeordneter Ordner)",
    folders_moving: "Verschieben...",
    folders_move_btn: "Verschieben",
    folders_subfolder: "Unterordner",
    folders_rename: "Umbenennen",
    folders_delete: "Löschen",
    folders_delete_q: "Ordner löschen?",
    folders_delete_body: "wird unwiderruflich gelöscht.",
    folders_structure: "Struktur",
    folders_click_to_open: "Klicken zum Öffnen",
    folders_none: "Noch keine Ordner",
    folders_none_hint: "Ordner werden automatisch erstellt.",
    folders_select: "Ordner auswählen",
    folders_select_hint: "Klicken Sie links auf einen Ordner um dessen Inhalt zu sehen.",
    folders_no_qr: "Keine QR-Codes in diesem Ordner",
    folders_assign_qr: "QR-Codes zuweisen",
    folders_yes_delete: "Ja, löschen",
    folders_cancel: "Abbrechen",
    folders_no_name: "(kein Name)",
    folders_edit_title: "Bearbeiten",
    folders_open_title: "Öffnen",
    folders_move_to_folder: "In Ordner verschieben",
    folders_remove_from: "Aus Ordner entfernen",
    folders_qr_codes_label: "QR-Codes",
    folders_users_label: "Nutzer",
    folders_all_qr: "Alle QR-Codes",
    folders_generic_error: "Fehler",
    // Clients (additional)
    clients_email: "E-Mail",
    clients_plan: "Plan",
    clients_label: "Beschriftung",
    clients_status: "Status",
    clients_manual: "Manuell",
    clients_from: "Von",
    clients_to: "Bis",
    clients_not_found: "Kunde nicht gefunden.",
    sign_out: "Abmelden",
  },
  en: {
    // Sidebar
    nav_dashboard: "Dashboard",
    nav_codes: "QR Codes",
    nav_settings: "Settings",
    nav_users: "Users",
    nav_clients: "Clients",
    nav_plans: "Plans",
    nav_plan_settings: "Plan Settings",
    nav_language: "Language",
    plan_settings_title: "Plan Settings",
    plan_settings_subtitle: "Edit prices and features for each plan.",
    plan_settings_price: "Price (CHF/month)",
    plan_settings_features: "Features (max. 4)",
    plan_settings_feature_placeholder: "e.g. Unlimited QR Codes",
    plan_settings_save: "Save",
    plan_settings_saved: "Saved!",
    plan_settings_edit: "Edit",
    plan_settings_cancel: "Cancel",
    plan_settings_stripe_warning: "⚠️ Price changes are NOT automatically applied in Stripe. Please also update the price manually in the Stripe Dashboard.",
    plan_settings_stripe_confirm: "Understood, save anyway",
    plan_settings_stripe_title: "Update Stripe manually",
    plan_settings_stripe_body: "Prices here and in Stripe are not linked. Changing the price here only updates the display. Stripe stays unchanged.",
    plan_settings_stripe_steps: "After saving, please in Stripe:",
    plan_settings_stripe_step1: "Create a new price for the product",
    plan_settings_stripe_step2: "Archive the old price",
    plan_settings_stripe_step3: "Update the new Price ID in the code",
    logout: "Logout",
    // Dashboard page
    dashboard_subtitle: "Manage your QR codes",
    create_qr: "Create QR Code",
    stat_total: "Total QR Codes",
    stat_active: "Active",
    stat_paused: "Paused",
    stat_phone: "With Phone",
    stat_website: "With Website",
    all_codes: "All QR Codes",
    no_codes: "No QR codes yet",
    no_codes_sub: "Create your first QR code",
    create_now: "Create now",
    col_name: "Name / Company",
    col_created: "Created",
    col_link: "Link",
    col_actions: "Actions",
    col_created_by: "Created by",
    delete_confirm: "Click again to confirm",
    delete: "Delete",
    // Codes page
    new_qr: "New QR Code",
    search_placeholder: "Search by name, company or ID...",
    no_results: "No QR codes found",
    unnamed: "Unnamed",
    edit: "Edit",
    codes_total: "QR Codes total",
    // Settings
    settings_title: "Settings",
    settings_subtitle: "Platform Settings",
    settings_placeholder: "Settings will be available in a future version.",
    settings_account: "Account",
    settings_plan_change: "Change plan",
    settings_email_change: "Change Email",
    settings_email_current: "Current Email",
    settings_email_new: "New Email Address",
    settings_email_saving: "Saving...",
    settings_email_btn: "Change Email",
    settings_email_error_same: "Please enter a different email address.",
    settings_email_success: "Confirmation email sent. Please check your inbox and confirm the new address.",
    settings_pw_change: "Change Password",
    settings_pw_current: "Current Password",
    settings_pw_new: "New Password",
    settings_pw_confirm: "Confirm New Password",
    settings_pw_saving: "Saving...",
    settings_pw_btn: "Change Password",
    settings_pw_error_match: "Passwords do not match.",
    settings_pw_error_short: "Minimum 6 characters required.",
    settings_pw_error_wrong: "Current password is incorrect.",
    settings_pw_success: "Password changed successfully.",
    // Create page
    create_title: "New QR Code",
    create_subtitle: "Fill in the fields and create your QR code",
    create_error: "Error creating. Please try again.",
    create_submit: "Create QR Code",
    // Edit page
    edit_title: "Edit QR Code",
    edit_success: "QR code successfully created!",
    saved: "Saved!",
    save_error: "Error saving.",
    open_page: "Open page",
    copy_link: "Copy link",
    copied: "Copied!",
    download_qr: "Download QR",
    save: "Save",
    // QRForm
    qr_label: "QR Code Name",
    qr_label_hint: "Only visible to you – helps identify it in the dashboard.",
    qr_label_placeholder: "e.g. Trade Fair 2025, Office Card",
    section_identity: "Identity",
    section_contact: "Contact Details",
    section_social: "Social Media",
    section_pdf: "File / PDF",
    section_notes: "Notes (internal) - only visible in the dashboard",
    field_first_name: "First Name",
    field_last_name: "Last Name",
    field_title: "Title / Position",
    field_company: "Company",
    field_logo: "Logo",
    field_logo_hint: "Direct image link (PNG, JPG, SVG)",
    upload_remove: "Remove",
    upload_uploading: "Uploading…",
    upload_error_size: "File too large. Maximum 14 MB.",
    upload_error_failed: "Upload failed. Please try again.",
    upload_logo: "Upload logo",
    upload_logo_hint: "Max. 14 MB · Automatically compressed if needed",
    upload_pdf: "Upload PDF",
    upload_pdf_open: "Open current file",
    upload_pdf_hint: "Max. 14 MB · PDF files only",
    pdf_option_upload: "Upload file",
    pdf_option_link: "Add link",
    link_label_placeholder: "e.g. Brochure, Price list…",
    link_add: "Add",
    links_max: "Maximum 4 entries reached",
    field_color: "Accent Color",
    field_color_hint: "Used as the background color on your QR business card.",
    upload_bg: "Upload Background Image",
    upload_bg_hint: "Max. 14 MB · If empty, the accent color is used.",
    field_phone: "Phone",
    field_email: "Email",
    field_website: "Website",
    field_street: "Street",
    field_street_nr: "No.",
    field_plz: "Postal Code",
    field_city: "City",
    field_linkedin: "LinkedIn URL",
    field_instagram: "Instagram URL",
    field_facebook: "Facebook URL",
    field_tiktok: "TikTok URL",
    field_snapchat: "Snapchat URL",
    field_x: "X (Twitter) URL",
    field_other_social: "Other (URL)",
    field_pdf_url: "PDF / File URL",
    field_pdf_label: "Button Label",
    field_notes: "Internal Note",
    field_notes_placeholder: "Only visible in the dashboard...",
    cancel: "Cancel",
    // Plan
    plan_label: "Plan",
    plan_limit_reached: "Limit reached for plan",
    plan_upgrade_hint: "Please upgrade your plan.",
    free_plan_banner: "You're on the Free plan. Limited to 1 QR code.",
    free_plan_upgrade: "Upgrade now →",
    plan_limit_ask_owner: "Ask the account owner to upgrade the plan",
    see_plans: "See Plans",
    // Upgrade page
    upgrade_title: "Upgrade Plan",
    upgrade_subtitle: "Choose the right plan for your needs",
    upgrade_current: "Current",
    upgrade_per_month: "/month",
    upgrade_current_plan: "Your current plan",
    upgrade_loading: "Loading…",
    upgrade_select: "Select",
    upgrade_no_expiry: "No expiry",
    upgrade_unlimited: "Unlimited",
    // Social placeholders
    social_placeholder: "username",
    qr_logo_in_center: "Show logo in QR code",
    delete_modal_title: "Delete QR Code?",
    delete_modal_body: "All data for this QR code will be permanently deleted. This action cannot be undone.",
    delete_modal_cancel: "Cancel",
    delete_modal_confirm: "Yes, delete",
    // Roles
    role_admin: "Admin",
    role_writer: "Writer",
    role_reader: "Reader",
    role_owner: "Owner",
    role_label: "Role",
    our_plans: "Our Plans",
    // Users page
    users_title: "User Management",
    users_subtitle: "Invite team members and manage their roles.",
    users_invite: "Invite User",
    users_invite_email: "Email Address",
    users_invite_role: "Role",
    users_invite_btn: "Invite",
    users_invite_sending: "Sending…",
    users_invite_success: "Invitation sent!",
    users_invite_error: "Error sending invite.",
    users_col_email: "Email",
    users_col_role: "Role",
    users_col_joined: "Joined",
    users_remove: "Remove",
    users_no_members: "No other members",
    users_resend: "Resend invitation",
    users_resend_sending: "Sending…",
    users_resend_success: "Invitation resent!",
    created_by: "Created by",
    // Clients page
    clients_title: "Clients",
    clients_subtitle: "Overview of all registered client accounts.",
    clients_no_clients: "No clients registered yet.",
    clients_col_qr: "QR Codes",
    clients_col_joined: "Registered",
    clients_change_plan: "Change plan",
    clients_delete: "Delete account",
    clients_delete_confirm: "Really delete?",
    clients_stat_total: "Total clients",
    clients_plan_modal_title: "Really change plan?",
    clients_plan_modal_stripe: "⚠️ If this client has an active Stripe subscription, it will NOT be updated automatically. Please update Stripe manually.",
    clients_plan_modal_confirm: "Yes, change plan",
    clients_plan_modal_cancel: "Cancel",
    clients_inactive_title: "Inactive clients",
    clients_inactive_body: "These clients have not created or updated any QR codes in the last 1 day(s).",
    clients_last_active: "Last active",
    clients_never_active: "No activity yet",
    clients_view: "View",
    // Client detail page
    client_detail_back: "Back to clients",
    client_detail_profile: "Profile",
    client_detail_members: "Team members",
    client_detail_qrcodes: "QR Codes",
    client_detail_total_scans: "Total scans",
    client_detail_joined: "Registered",
    client_detail_last_active: "Last activity",
    client_detail_stripe: "Stripe",
    client_detail_no_members: "No team members",
    client_detail_no_qr: "No QR codes yet",
    client_detail_active: "Active",
    client_detail_paused: "Paused",
    client_detail_scans: "Scans",
    client_detail_role: "Role",
    client_detail_joined_team: "Joined",
    // Paused QR page
    qr_paused_title: "QR Code paused",
    qr_paused_body: "This QR code is currently paused. The owner needs to upgrade their plan to reactivate it.",
    // Onboarding
    onboarding_title: "Welcome! 👋",
    onboarding_subtitle: "Get started in 3 simple steps:",
    onboarding_step1: "Create your first QR code",
    onboarding_step2: "Share the link or print the QR code",
    onboarding_step3: "Edit your details anytime. The QR code stays the same.",
    onboarding_dismiss: "Got it, let's go!",
    // Scan analytics
    scans_total: "Total scans",
    scans_label: "Scans",
    scans_today: "Today",
    scans_last7: "Last 7 days",
    field_description: "Description",
    // Theme
    field_theme: "Card Design",
    theme_classic: "Classic",
    theme_dark: "Dark",
    theme_minimal: "Minimal",
    // Codes filter
    filter_all: "All",
    filter_active: "Active",
    filter_paused: "Paused",
    qr_paused_badge: "Paused. Upgrade plan to reactivate.",
    sort_newest: "Newest first",
    sort_oldest: "Oldest first",
    sort_name: "Name A–Z",
    export_csv: "Export CSV",
    contact_support: "Contact support",
    settings_support_email_title: "Contact Email",
    settings_support_email_hint: "Shown to team members when a save error occurs.",
    settings_support_email_btn: "Save",
    // Landing page
    landing_call: "Call",
    landing_email_default: "Email",
    landing_website_default: "Website",
    landing_document: "Document",
    landing_link: "Link",
    landing_save_contact: "Save contact",
    landing_share: "Share",
    landing_copied: "Copied!",
    landing_lead_btn: "Leave your contact",
    landing_lead_title: "Leave your contact",
    landing_lead_subtitle_suffix: "will be in touch.",
    landing_lead_thanks: "Thank you!",
    landing_lead_received: "Your contact has been received.",
    landing_lead_close: "Close",
    landing_lead_name: "Name",
    landing_lead_email: "Email",
    landing_lead_comment: "Comment",
    landing_lead_optional: "(optional)",
    landing_lead_name_ph: "Your full name",
    landing_lead_email_ph: "your@email.com",
    landing_lead_comment_ph: "Any message or note…",
    landing_lead_consent: "I agree that my name, email and message may be stored and used to contact me. I can withdraw my consent at any time.",
    landing_lead_consent_required: "Please tick the consent checkbox to continue.",
    landing_lead_sending: "Sending…",
    landing_lead_send: "Send contact",
    landing_lead_error_generic: "Something went wrong.",
    landing_lead_error_network: "Network error. Please try again.",
    // Dashboard page
    dashboard_title: "Dashboard",
    kpi_total_qrs: "Total QR Codes",
    kpi_total_scans: "Total Scans",
    kpi_unique_visitors: "Unique Visitors",
    kpi_returning: "Returning",
    kpi_conversion_rate: "Conversion Rate",
    dashboard_active_codes: "Active QR Codes",
    dashboard_paused_codes: "Paused QR Codes",
    chart_title: "Scans Over Time",
    chart_subtitle: "Total scans across all QR codes",
    chart_no_scans: "No scans in this period",
    recent_codes: "Recent QR Codes",
    view_all: "View all",
    no_qrs_yet: "No QR codes yet",
    create_first: "Create first",
    by_label: "By",
    interactions_title: "Interactions",
    interactions_subtitle: "Click counts across all QR codes",
    interactions_total: "total",
    no_interactions: "No interactions tracked yet",
    top_qrs_title: "Top Performing QR Codes",
    top_qrs_subtitle: "Ranked by total scan count",
    no_scan_data: "No scan data yet",
    upgrade_plan_btn: "Upgrade Plan →",
    evt_phone: "Phone",
    evt_email: "Email",
    evt_website: "Website",
    evt_pdf: "PDF",
    evt_link: "Link",
    evt_save_contact: "Save Contact",
    evt_share: "Share",
    evt_linkedin: "LinkedIn",
    evt_instagram: "Instagram",
    evt_facebook: "Facebook",
    evt_tiktok: "TikTok",
    evt_snapchat: "Snapchat",
    evt_x: "X",
    evt_other: "Other",
    evt_lead_open: "Lead Form Opened",
    evt_lead_submit: "Lead Submitted",
    // Edit page
    edit_qr_ready: "Your QR code is ready. Download it below or make any adjustments and save.",
    edit_basic_info: "Basic Information",
    edit_dest_folder: "Destination Folder",
    optional: "(optional)",
    // Settings page (additional)
    settings_subtitle_full: "Manage your account orchestration and global platform preferences.",
    settings_account_info: "Account Information",
    settings_full_name: "Full Name",
    settings_email_label: "Email Address",
    settings_role_label: "Role:",
    settings_plan_change_short: "Change",
    settings_security: "Security",
    settings_2fa: "Two-Factor Auth",
    settings_2fa_hint: "Extra login security via authenticator app",
    settings_2fa_disabled: "Disabled by admin",
    settings_pw_confirm_label: "Confirm Password",
    // Upgrade page
    upgrade_subscription_mgmt: "Subscription Management",
    upgrade_active_btn: "Active",
    upgrade_stay_free: "Stay on Free",
    upgrade_compare_features: "Compare full capabilities",
    upgrade_core_feature: "Core Feature",
    upgrade_plan_free: "Free",
    upgrade_plan_star: "Star",
    upgrade_plan_premium: "Premium",
    // Leads
    leads_title: "Leads",
    leads_subtitle: "Contacts submitted via your QR cards",
    leads_search_ph: "Search by name, email or QR card…",
    leads_all_members: "All Members",
    leads_none_search: "No leads match your search",
    leads_none: "No leads yet",
    leads_none_hint: "Enable Lead Capture on a QR card to start collecting contacts.",
    leads_count_one: "lead",
    leads_count_many: "leads",
    leads_open_live: "Open Live Card",
    leads_edit: "Edit",
    leads_analytics: "Analytics",
    leads_preview_qr: "Preview QR code",
    leads_edit_card: "Edit QR card",
    leads_qr_card: "QR Card",
    // NFC
    nfc_title: "NFC Cards",
    nfc_subtitle: "Register physical NFC cards and assign them to profiles",
    nfc_register: "Register NFC Card",
    nfc_register_hint: "Enter the unique ID printed on or programmed into the card",
    nfc_card_uid: "Card UID / Code *",
    nfc_label_optional: "Label (optional)",
    nfc_assign_profile: "Assign to profile (optional)",
    nfc_no_cards: "No NFC cards registered",
    nfc_no_cards_hint: "Register your first NFC card to start assigning it to profiles",
    nfc_no_contacts: "No contacts found",
    nfc_save: "Save",
    nfc_cancel: "Cancel",
    nfc_not_assigned: "Not assigned",
    // Folders
    folders_title: "Folders",
    folders_total_suffix: "folders total",
    folders_load_error: "Failed to load",
    folders_name_ph: "Folder name",
    folders_save: "Save",
    folders_create: "Create",
    folders_move: "Move folder",
    folders_move_for: "New parent for",
    folders_root_option: "— Root (no parent folder)",
    folders_moving: "Moving...",
    folders_move_btn: "Move",
    folders_subfolder: "Subfolder",
    folders_rename: "Rename",
    folders_delete: "Delete",
    folders_delete_q: "Delete folder?",
    folders_delete_body: "will be permanently deleted.",
    folders_structure: "Structure",
    folders_click_to_open: "Click to open",
    folders_none: "No folders yet",
    folders_none_hint: "Folders are created automatically.",
    folders_select: "Select a folder",
    folders_select_hint: "Click on a folder on the left to view its contents.",
    folders_no_qr: "No QR codes in this folder",
    folders_assign_qr: "Assign QR codes",
    folders_yes_delete: "Yes, delete",
    folders_cancel: "Cancel",
    folders_no_name: "(no name)",
    folders_edit_title: "Edit",
    folders_open_title: "Open",
    folders_move_to_folder: "Move to folder",
    folders_remove_from: "Remove from folder",
    folders_qr_codes_label: "QR codes",
    folders_users_label: "Users",
    folders_all_qr: "All QR codes",
    folders_generic_error: "Error",
    // Clients (additional)
    clients_email: "Email",
    clients_plan: "Plan",
    clients_label: "Label",
    clients_status: "Status",
    clients_manual: "Manual",
    clients_from: "From",
    clients_to: "To",
    clients_not_found: "Client not found.",
    sign_out: "Sign out",
  },
};

type Translations = typeof t.de;

interface LangContextType {
  lang: Lang;
  tr: Translations;
  toggleLang: () => void;
}

const LangContext = createContext<LangContextType>({
  lang: "de",
  tr: t.de,
  toggleLang: () => {},
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("de");

  useEffect(() => {
    const stored = localStorage.getItem("dashboard_lang") as Lang | null;
    if (stored === "en" || stored === "de") setLang(stored);
  }, []);

  function toggleLang() {
    setLang((prev) => {
      const next = prev === "de" ? "en" : "de";
      localStorage.setItem("dashboard_lang", next);
      return next;
    });
  }

  return (
    <LangContext.Provider value={{ lang, tr: t[lang], toggleLang }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
