"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Lang = "de" | "en";

export const t = {
  de: {
    // Sidebar
    nav_dashboard: "Dashboard",
    nav_codes: "QR Codes",
    nav_settings: "Einstellungen",
    nav_users: "Benutzer",
    nav_clients: "Kunden",
    nav_language: "Sprache",
    logout: "Abmelden",
    // Dashboard page
    dashboard_subtitle: "Verwalten Sie Ihre QR Codes",
    create_qr: "QR Code erstellen",
    stat_total: "Gesamt QR Codes",
    stat_phone: "Mit Telefon",
    stat_website: "Mit Website",
    all_codes: "Alle QR Codes",
    no_codes: "Noch keine QR Codes",
    no_codes_sub: "Erstellen Sie Ihren ersten QR Code",
    create_now: "Jetzt erstellen",
    col_name: "Name / Musterfirma",
    col_created: "Erstellt",
    col_link: "Link",
    col_actions: "Aktionen",
    col_created_by: "Erstellt von",
    delete_confirm: "Nochmal klicken zum Bestätigen",
    delete: "Löschen",
    // Codes page
    new_qr: "Neuer QR Code",
    search_placeholder: "Suche nach Name, Musterfirma oder ID...",
    no_results: "Keine QR Codes gefunden",
    unnamed: "Unbenannt",
    edit: "Bearbeiten",
    codes_total: "QR Codes gesamt",
    // Settings
    settings_title: "Einstellungen",
    settings_subtitle: "Plattform-Einstellungen",
    settings_placeholder: "Einstellungen werden in einer zukünftigen Version verfügbar sein.",
    settings_account: "Konto",
    settings_plan_change: "Plan ändern",
    settings_email_change: "E-Mail ändern",
    settings_email_current: "Aktuelle E-Mail",
    settings_email_new: "Neue E-Mail-Adresse",
    settings_email_saving: "Wird gespeichert...",
    settings_email_btn: "E-Mail ändern",
    settings_email_error_same: "Bitte eine andere E-Mail-Adresse eingeben.",
    settings_email_success: "Bestätigungs-E-Mail wurde gesendet. Bitte prüfen Sie Ihr Postfach und bestätigen Sie die neue Adresse.",
    settings_pw_change: "Passwort ändern",
    settings_pw_current: "Aktuelles Passwort",
    settings_pw_new: "Neues Passwort",
    settings_pw_confirm: "Neues Passwort bestätigen",
    settings_pw_saving: "Wird gespeichert...",
    settings_pw_btn: "Passwort ändern",
    settings_pw_error_match: "Passwörter stimmen nicht überein.",
    settings_pw_error_short: "Mindestens 6 Zeichen erforderlich.",
    settings_pw_error_wrong: "Aktuelles Passwort ist falsch.",
    settings_pw_success: "Passwort erfolgreich geändert.",
    // Create page
    create_title: "Neuer QR Code",
    create_subtitle: "Füllen Sie die Felder aus und erstellen Sie Ihren QR Code",
    create_error: "Fehler beim Erstellen. Bitte versuchen Sie es erneut.",
    create_submit: "QR Code erstellen",
    // Edit page
    edit_title: "QR Code bearbeiten",
    edit_success: "QR Code erfolgreich erstellt!",
    saved: "Gespeichert!",
    save_error: "Fehler beim Speichern.",
    open_page: "Seite öffnen",
    copy_link: "Link kopieren",
    copied: "Kopiert!",
    download_qr: "QR herunterladen",
    save: "Speichern",
    // QRForm
    qr_label: "QR Code Name",
    qr_label_hint: "Nur für Sie sichtbar – hilft beim Erkennen im Dashboard.",
    qr_label_placeholder: "z.B. Messe 2026, Visitenkarte Büro",
    section_identity: "Angaben",
    section_contact: "Kontaktdaten",
    section_social: "Social Media",
    section_pdf: "Dateien / PDF",
    section_notes: "Notizen (intern)",
    field_first_name: "Vorname",
    field_last_name: "Name",
    field_title: "Titel / Position",
    field_company: "Musterfirma",
    field_logo: "Logo / Profilbild",
    field_logo_hint: "Direkter Bildlink (PNG, JPG, SVG)",
    upload_remove: "Entfernen",
    upload_uploading: "Wird hochgeladen…",
    upload_error_size: "Dateien zu groß. Maximum 14 MB.",
    upload_error_failed: "Upload fehlgeschlagen. Bitte erneut versuchen.",
    upload_logo: "Logo hochladen",
    upload_logo_hint: "Max. 14 MB · Wird automatisch komprimiert wenn nötig",
    upload_pdf: "PDF hochladen",
    upload_pdf_open: "Aktuelle Dateien öffnen",
    upload_pdf_hint: "Max. 14 MB · Nur PDF-Dateien",
    pdf_option_upload: "Dateien hochladen",
    pdf_option_link: "Link hinzufügen",
    link_label_placeholder: "z.B. Broschüre, Preisliste…",
    link_add: "Hinzufügen",
    links_max: "Maximum 4 Einträge erreicht",
    field_color: "Akzentfarbe",
    field_color_hint: "Wird als Hintergrundfarbe auf Ihrer QR-Visitenkarte verwendet.",
    upload_bg: "Hintergrundbild hochladen",
    upload_bg_hint: "Max. 14 MB · Wenn leer, wird die Akzentfarbe verwendet.",
    field_phone: "Telefon",
    field_email: "E-Mail",
    field_website: "Webseite",
    field_street: "Strasse",
    field_street_nr: "Nr.",
    field_plz: "PLZ",
    field_city: "Ort",
    field_linkedin: "LinkedIn URL",
    field_instagram: "Instagram URL",
    field_facebook: "Facebook URL",
    field_tiktok: "TikTok URL",
    field_snapchat: "Snapchat URL",
    field_x: "X (Twitter) URL",
    field_other_social: "Andere (URL)",
    field_pdf_url: "PDF / Datei URL",
    field_pdf_label: "Button-Beschriftung",
    field_notes: "Interne Notiz",
    field_notes_placeholder: "Nur im Dashboard sichtbar...",
    cancel: "Abbrechen",
    // Plan
    plan_label: "Plan",
    plan_limit_reached: "Limit erreicht für Plan",
    plan_upgrade_hint: "Bitte upgraden Sie Ihren Plan.",
    free_plan_banner: "Du nutzt den kostenlosen Plan – nur 1 QR Code möglich.",
    free_plan_upgrade: "Jetzt upgraden →",
    qr_logo_in_center: "Logo im QR Code anzeigen",
    delete_modal_title: "QR Code löschen?",
    delete_modal_body: "Alle Daten dieses QR Codes werden unwiderruflich gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.",
    delete_modal_cancel: "Abbrechen",
    delete_modal_confirm: "Ja, löschen",
    // Roles
    role_admin: "Admin",
    role_writer: "Bearbeiter",
    role_reader: "Leser",
    role_label: "Rolle",
    our_plans: "Unsere Pläne",
    // Users page
    users_title: "Benutzerverwaltung",
    users_subtitle: "Laden Sie Teammitglieder ein und verwalten Sie deren Rollen.",
    users_invite: "Benutzer einladen",
    users_invite_email: "E-Mail-Adresse",
    users_invite_role: "Rolle",
    users_invite_btn: "Einladen",
    users_invite_sending: "Wird gesendet…",
    users_invite_success: "Einladung gesendet!",
    users_invite_error: "Fehler beim Senden.",
    users_col_email: "E-Mail",
    users_col_role: "Rolle",
    users_col_joined: "Beigetreten",
    users_remove: "Entfernen",
    users_no_members: "Keine weiteren Mitglieder",
    users_resend: "Einladung erneut senden",
    users_resend_sending: "Wird gesendet…",
    users_resend_success: "Einladung erneut gesendet!",
    created_by: "Erstellt von",
    // Clients page
    clients_title: "Kunden",
    clients_subtitle: "Übersicht aller registrierten Kunden-Accounts.",
    clients_no_clients: "Noch keine Kunden registriert.",
    clients_col_qr: "QR Codes",
    clients_col_joined: "Registriert",
    clients_change_plan: "Plan ändern",
    clients_delete: "Konto löschen",
    clients_delete_confirm: "Wirklich löschen?",
    clients_stat_total: "Kunden gesamt",
  },
  en: {
    // Sidebar
    nav_dashboard: "Dashboard",
    nav_codes: "QR Codes",
    nav_settings: "Settings",
    nav_users: "Users",
    nav_clients: "Clients",
    nav_language: "Language",
    logout: "Logout",
    // Dashboard page
    dashboard_subtitle: "Manage your QR codes",
    create_qr: "Create QR Code",
    stat_total: "Total QR Codes",
    stat_phone: "With Phone",
    stat_website: "With Website",
    all_codes: "All QR Codes",
    no_codes: "No QR codes yet",
    no_codes_sub: "Create your first QR code",
    create_now: "Create now",
    col_name: "Name / Company",
    col_created: "Created",
    col_link: "Link",
    col_actions: "Actions",
    col_created_by: "Created by",
    delete_confirm: "Click again to confirm",
    delete: "Delete",
    // Codes page
    new_qr: "New QR Code",
    search_placeholder: "Search by name, company or ID...",
    no_results: "No QR codes found",
    unnamed: "Unnamed",
    edit: "Edit",
    codes_total: "QR Codes total",
    // Settings
    settings_title: "Settings",
    settings_subtitle: "Platform Settings",
    settings_placeholder: "Settings will be available in a future version.",
    settings_account: "Account",
    settings_plan_change: "Change plan",
    settings_email_change: "Change Email",
    settings_email_current: "Current Email",
    settings_email_new: "New Email Address",
    settings_email_saving: "Saving...",
    settings_email_btn: "Change Email",
    settings_email_error_same: "Please enter a different email address.",
    settings_email_success: "Confirmation email sent. Please check your inbox and confirm the new address.",
    settings_pw_change: "Change Password",
    settings_pw_current: "Current Password",
    settings_pw_new: "New Password",
    settings_pw_confirm: "Confirm New Password",
    settings_pw_saving: "Saving...",
    settings_pw_btn: "Change Password",
    settings_pw_error_match: "Passwords do not match.",
    settings_pw_error_short: "Minimum 6 characters required.",
    settings_pw_error_wrong: "Current password is incorrect.",
    settings_pw_success: "Password changed successfully.",
    // Create page
    create_title: "New QR Code",
    create_subtitle: "Fill in the fields and create your QR code",
    create_error: "Error creating. Please try again.",
    create_submit: "Create QR Code",
    // Edit page
    edit_title: "Edit QR Code",
    edit_success: "QR code successfully created!",
    saved: "Saved!",
    save_error: "Error saving.",
    open_page: "Open page",
    copy_link: "Copy link",
    copied: "Copied!",
    download_qr: "Download QR",
    save: "Save",
    // QRForm
    qr_label: "QR Code Name",
    qr_label_hint: "Only visible to you – helps identify it in the dashboard.",
    qr_label_placeholder: "e.g. Trade Fair 2025, Office Card",
    section_identity: "Identity",
    section_contact: "Contact Details",
    section_social: "Social Media",
    section_pdf: "File / PDF",
    section_notes: "Notes (internal) - only visible in the dashboard",
    field_first_name: "First Name",
    field_last_name: "Last Name",
    field_title: "Title / Position",
    field_company: "Company",
    field_logo: "Logo",
    field_logo_hint: "Direct image link (PNG, JPG, SVG)",
    upload_remove: "Remove",
    upload_uploading: "Uploading…",
    upload_error_size: "File too large. Maximum 14 MB.",
    upload_error_failed: "Upload failed. Please try again.",
    upload_logo: "Upload logo",
    upload_logo_hint: "Max. 14 MB · Automatically compressed if needed",
    upload_pdf: "Upload PDF",
    upload_pdf_open: "Open current file",
    upload_pdf_hint: "Max. 14 MB · PDF files only",
    pdf_option_upload: "Upload file",
    pdf_option_link: "Add link",
    link_label_placeholder: "e.g. Brochure, Price list…",
    link_add: "Add",
    links_max: "Maximum 4 entries reached",
    field_color: "Accent Color",
    field_color_hint: "Used as the background color on your QR business card.",
    upload_bg: "Upload Background Image",
    upload_bg_hint: "Max. 14 MB · If empty, the accent color is used.",
    field_phone: "Phone",
    field_email: "Email",
    field_website: "Website",
    field_street: "Street",
    field_street_nr: "No.",
    field_plz: "Postal Code",
    field_city: "City",
    field_linkedin: "LinkedIn URL",
    field_instagram: "Instagram URL",
    field_facebook: "Facebook URL",
    field_tiktok: "TikTok URL",
    field_snapchat: "Snapchat URL",
    field_x: "X (Twitter) URL",
    field_other_social: "Other (URL)",
    field_pdf_url: "PDF / File URL",
    field_pdf_label: "Button Label",
    field_notes: "Internal Note",
    field_notes_placeholder: "Only visible in the dashboard...",
    cancel: "Cancel",
    // Plan
    plan_label: "Plan",
    plan_limit_reached: "Limit reached for plan",
    plan_upgrade_hint: "Please upgrade your plan.",
    free_plan_banner: "You're on the Free plan — limited to 1 QR code.",
    free_plan_upgrade: "Upgrade now →",
    qr_logo_in_center: "Show logo in QR code",
    delete_modal_title: "Delete QR Code?",
    delete_modal_body: "All data for this QR code will be permanently deleted. This action cannot be undone.",
    delete_modal_cancel: "Cancel",
    delete_modal_confirm: "Yes, delete",
    // Roles
    role_admin: "Admin",
    role_writer: "Writer",
    role_reader: "Reader",
    role_label: "Role",
    our_plans: "Our Plans",
    // Users page
    users_title: "User Management",
    users_subtitle: "Invite team members and manage their roles.",
    users_invite: "Invite User",
    users_invite_email: "Email Address",
    users_invite_role: "Role",
    users_invite_btn: "Invite",
    users_invite_sending: "Sending…",
    users_invite_success: "Invitation sent!",
    users_invite_error: "Error sending invite.",
    users_col_email: "Email",
    users_col_role: "Role",
    users_col_joined: "Joined",
    users_remove: "Remove",
    users_no_members: "No other members",
    users_resend: "Resend invitation",
    users_resend_sending: "Sending…",
    users_resend_success: "Invitation resent!",
    created_by: "Created by",
    // Clients page
    clients_title: "Clients",
    clients_subtitle: "Overview of all registered client accounts.",
    clients_no_clients: "No clients registered yet.",
    clients_col_qr: "QR Codes",
    clients_col_joined: "Registered",
    clients_change_plan: "Change plan",
    clients_delete: "Delete account",
    clients_delete_confirm: "Really delete?",
    clients_stat_total: "Total clients",
  },
};

type Translations = typeof t.de;

interface LangContextType {
  lang: Lang;
  tr: Translations;
  toggleLang: () => void;
}

const LangContext = createContext<LangContextType>({
  lang: "de",
  tr: t.de,
  toggleLang: () => {},
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("de");

  useEffect(() => {
    const stored = localStorage.getItem("dashboard_lang") as Lang | null;
    if (stored === "en" || stored === "de") setLang(stored);
  }, []);

  function toggleLang() {
    setLang((prev) => {
      const next = prev === "de" ? "en" : "de";
      localStorage.setItem("dashboard_lang", next);
      return next;
    });
  }

  return (
    <LangContext.Provider value={{ lang, tr: t[lang], toggleLang }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
