"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { BRAND_NAME } from "./brand";

export type Lang = "de" | "en";

export const t = {
  de: {
    // Sidebar
    nav_dashboard: "Dashboard",
    nav_codes: "QR Codes",
    branding_color_clear: "Farbe entfernen",
    nav_analytics: "Analyse",
    analytics_overview_title: "Analyse-Übersicht",
    analytics_overview_subtitle: "Leistung Ihrer QR-Codes auf einen Blick",
    analytics_col_code: "QR-Code",
    analytics_col_total: "Scans gesamt",
    analytics_col_7d: "Letzte 7 Tage",
    analytics_col_unique: "Eindeutige Besucher",
    analytics_col_leads: "Leads",
    analytics_col_conversion: "Conversion",
    analytics_col_last_scan: "Letzter Scan",
    analytics_empty: "Noch keine QR-Codes — sobald Sie einen erstellen, erscheinen hier die Statistiken.",
    analytics_loading: "Wird geladen…",
    analytics_never: "Noch nie",
    nav_settings: "Einstellungen",
    nav_users: "Benutzer",
    nav_clients: "Kunden",
    nav_plans: "Pläne",
    nav_trash: "Papierkorb",
    nav_plan_settings: "Plan-Einstellungen",
    nav_language: "Sprache",
    plan_settings_title: "Plan-Einstellungen",
    plan_settings_subtitle: "Preise und Funktionen für jeden Plan bearbeiten.",
    plan_settings_price: "Preis (CHF/Monat)",
    plan_settings_features: "Funktionen (max. 4)",
    plan_settings_feature_placeholder: "z.B. Unbegrenzte QR Codes",
    plan_settings_save: "Speichern",
    plan_settings_saved: "Gespeichert!",
    plan_settings_edit: "Bearbeiten",
    plan_settings_cancel: "Abbrechen",
    plan_settings_stripe_warning: "⚠️ Preisänderungen werden NICHT automatisch in Stripe übernommen. Bitte den Preis auch im Stripe-Dashboard manuell aktualisieren.",
    plan_settings_stripe_banner_title: "Stripe-Preise müssen synchron bleiben",
    plan_settings_stripe_banner_body: "Wenn Sie hier einen Plan-Preis ändern, müssen Sie auch den entsprechenden Produktpreis in Ihrem Stripe-Dashboard aktualisieren. Nicht übereinstimmende Preise führen zu Konflikten bei Checkout und Abrechnung – Kunden könnten einen anderen Betrag belastet bekommen als auf der Website angezeigt.",
    plan_settings_stripe_banner_link: "Stripe-Produkt-Dashboard öffnen →",
    plan_settings_stripe_confirm: "Verstanden, trotzdem speichern",
    plan_settings_stripe_title: "Stripe manuell aktualisieren",
    plan_settings_stripe_body: "Preise hier und in Stripe sind nicht verknüpft. Eine Änderung hier aktualisiert nur die Anzeige. Stripe bleibt unverändert.",
    plan_settings_stripe_steps: "Nach dem Speichern bitte in Stripe:",
    plan_settings_stripe_step1: "Neuen Preis für das Produkt erstellen",
    plan_settings_stripe_step2: "Alten Preis archivieren",
    plan_settings_stripe_step3: "Neue Preis-ID im Code hinterlegen",
    logout: "Abmelden",
    // Dashboard page
    dashboard_subtitle: "Verwalten Sie Ihre QR Codes",
    create_qr: "QR Code erstellen",
    stat_total: "Gesamt QR Codes",
    stat_active: "Aktiv",
    stat_paused: "Pausiert",
    stat_phone: "Mit Telefon",
    stat_website: "Mit Website",
    all_codes: "Alle QR Codes",
    no_codes: "Noch keine QR Codes",
    no_codes_sub: "Erstellen Sie Ihren ersten QR Code",
    create_now: "Jetzt erstellen",
    col_name: "Name / Musterfirma",
    col_created: "Erstellt",
    col_link: "Link",
    col_actions: "Aktionen",
    col_created_by: "Erstellt von",
    delete_confirm: "Nochmal klicken zum Bestätigen",
    delete: "Löschen",
    // Codes page
    new_qr: "Neuer QR Code",
    search_placeholder: "Suche nach Name, Musterfirma oder ID...",
    no_results: "Keine QR Codes gefunden",
    unnamed: "Unbenannt",
    edit: "Bearbeiten",
    codes_total: "QR Codes gesamt",
    // Settings
    settings_title: "Einstellungen",
    settings_subtitle: "Plattform-Einstellungen",
    settings_placeholder: "Einstellungen werden in einer zukünftigen Version verfügbar sein.",
    settings_account: "Konto",
    settings_plan_change: "Plan ändern",
    settings_email_change: "E-Mail ändern",
    settings_email_current: "Aktuelle E-Mail",
    settings_email_new: "Neue E-Mail-Adresse",
    settings_email_saving: "Wird gespeichert...",
    settings_email_btn: "E-Mail ändern",
    settings_email_error_same: "Bitte eine andere E-Mail-Adresse eingeben.",
    settings_email_success: "Bestätigungs-E-Mail wurde an die neue Adresse gesendet. Bitte prüfen Sie Ihr Postfach und klicken Sie den Link, um die Änderung abzuschließen.",
    settings_account_saved: "Änderungen gespeichert.",
    settings_pw_change: "Passwort ändern",
    settings_pw_current: "Aktuelles Passwort",
    settings_pw_new: "Neues Passwort",
    settings_pw_confirm: "Neues Passwort bestätigen",
    settings_pw_saving: "Wird gespeichert...",
    settings_pw_btn: "Passwort ändern",
    settings_pw_error_match: "Passwörter stimmen nicht überein.",
    settings_pw_error_short: "Mindestens 6 Zeichen erforderlich.",
    settings_pw_error_wrong: "Aktuelles Passwort ist falsch.",
    settings_pw_success: "Passwort erfolgreich geändert.",
    // Create page
    create_title: "Neuer QR Code",
    create_subtitle: "Füllen Sie die Felder aus und erstellen Sie Ihren QR Code",
    create_error: "Fehler beim Erstellen. Bitte versuchen Sie es erneut.",
    create_submit: "QR Code erstellen",
    // Edit page
    edit_title: "QR Code bearbeiten",
    edit_success: "QR Code erfolgreich erstellt!",
    saved: "Gespeichert!",
    save_error: "Fehler beim Speichern.",
    open_page: "Seite öffnen",
    copy_link: "Link kopieren",
    copied: "Kopiert!",
    download_qr: "QR herunterladen",
    save: "Speichern",
    // QRForm
    qr_label: "QR Code Name",
    qr_label_hint: "Nur für Sie sichtbar – hilft beim Erkennen im Dashboard.",
    qr_label_placeholder: "z.B. Messe 2026, Visitenkarte Büro",
    section_identity: "Angaben",
    section_contact: "Kontaktdaten",
    section_social: "Social Media",
    section_pdf: "Dateien / PDF",
    section_notes: "Notizen (intern)",
    field_first_name: "Vorname",
    field_last_name: "Name",
    field_title: "Titel / Position",
    field_company: "Musterfirma",
    field_logo: "Logo / Profilbild",
    field_logo_hint: "Direkter Bildlink (PNG, JPG, SVG)",
    upload_remove: "Entfernen",
    upload_uploading: "Wird hochgeladen…",
    upload_error_size: "Dateien zu groß. Maximum 14 MB.",
    upload_error_failed: "Upload fehlgeschlagen. Bitte erneut versuchen.",
    upload_logo: "Logo hochladen",
    upload_logo_hint: "Max. 14 MB · Wird automatisch komprimiert wenn nötig",
    upload_pdf: "PDF hochladen",
    upload_pdf_open: "Aktuelle Dateien öffnen",
    upload_pdf_hint: "Max. 14 MB · Nur PDF-Dateien",
    pdf_option_upload: "Dateien hochladen",
    pdf_option_link: "Link hinzufügen",
    link_label_placeholder: "z.B. Broschüre, Preisliste…",
    link_add: "Hinzufügen",
    links_max: "Maximum 4 Einträge erreicht",
    field_color: "Akzentfarbe",
    field_color_hint: "Wird als Hintergrundfarbe auf Ihrer QR-Visitenkarte verwendet.",
    upload_bg: "Hintergrundbild hochladen",
    upload_bg_hint: "Max. 14 MB · Wenn leer, wird die Akzentfarbe verwendet.",
    field_phone: "Telefon",
    field_email: "E-Mail",
    field_website: "Webseite",
    field_street: "Strasse",
    field_street_nr: "Nr.",
    field_plz: "PLZ",
    field_city: "Ort",
    field_linkedin: "LinkedIn URL",
    field_instagram: "Instagram URL",
    field_facebook: "Facebook URL",
    field_tiktok: "TikTok URL",
    field_snapchat: "Snapchat URL",
    field_x: "X (Twitter) URL",
    field_other_social: "Andere (URL)",
    field_pdf_url: "PDF / Datei URL",
    field_pdf_label: "Button-Beschriftung",
    field_notes: "Interne Notiz",
    field_notes_placeholder: "Nur im Dashboard sichtbar...",
    cancel: "Abbrechen",
    // Plan
    plan_label: "Plan",
    plan_limit_reached: "Limit erreicht für Plan",
    plan_upgrade_hint: "Bitte upgraden Sie Ihren Plan.",
    free_plan_banner: "Du nutzt den kostenlosen Plan – nur 1 QR Code möglich.",
    free_plan_upgrade: "Jetzt upgraden →",
    plan_limit_ask_owner: "Bitte den Account-Inhaber, den Plan zu upgraden",
    see_plans: "Pläne ansehen",
    // Upgrade page
    upgrade_title: "Plan upgraden",
    upgrade_subtitle: "Wählen Sie den passenden Plan für Ihre Bedürfnisse",
    upgrade_current: "Aktuell",
    upgrade_per_month: "/Monat",
    upgrade_current_plan: "Ihr aktueller Plan",
    upgrade_loading: "Wird geladen…",
    upgrade_select: "wählen",
    upgrade_no_expiry: "Kein Ablauf",
    upgrade_unlimited: "Unbegrenzt",
    // Social placeholders
    social_placeholder: "Benutzername",
    qr_logo_in_center: "Logo im QR Code anzeigen",
    delete_modal_title: "QR Code löschen?",
    delete_modal_body: "Alle Daten dieses QR Codes werden unwiderruflich gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.",
    delete_modal_cancel: "Abbrechen",
    delete_modal_confirm: "Ja, löschen",
    pause_modal_pause_folder: "Gesamten Ordner pausieren?",
    pause_modal_pause_qr: "Diesen QR Code pausieren?",
    pause_modal_activate_folder: "Gesamten Ordner aktivieren?",
    pause_modal_activate_qr: "Diesen QR Code aktivieren?",
    pause_modal_pause_body: "Wer diesen QR Code scannt, wird auf qr-card.ch weitergeleitet statt auf deine Kontaktseite.",
    pause_modal_pause_body_folder: "Jeder, der einen QR-Code aus diesem Ordner scannt, wird zu qr-card.ch weitergeleitet anstatt zum QR-Card-Link.",
    pause_modal_activate_body: "Der QR Code wird wieder aktiv und Besucher sehen deine Kontaktseite.",
    pause_modal_activate_body_folder: "Alle QR-Codes in diesem Ordner werden wieder aktiviert, und Besucher werden zum entsprechenden QR-Card-Link weitergeleitet.",
    pause_modal_redirect_note_prefix: "Pausierte QR Codes leiten weiter auf",
    pause_modal_cancel: "Abbrechen",
    pause_modal_confirm_pause: "Ja, pausieren",
    pause_modal_confirm_activate: "Ja, aktivieren",
    // Roles
    role_admin: "Admin",
    role_writer: "Bearbeiter",
    role_owner: "Owner",
    role_label: "Rolle",
    // Role permissions card
    role_perm_title: "Rollenberechtigungen",
    role_perm_subtitle: "Was jede Rolle auf der Plattform tun kann.",
    role_perm_owner_subtitle: "Kontoinhaber",
    role_perm_admin_subtitle: "Team-Manager",
    role_perm_writer_subtitle: "Inhaltsbearbeiter",
    role_perm_create_edit_delete: "QR Codes erstellen, bearbeiten & löschen",
    role_perm_create_edit_delete_restore: "QR Codes erstellen, bearbeiten & löschen, mit 72h Wiederherstellung",
    role_perm_create_edit: "QR Codes erstellen & bearbeiten",
    role_perm_view_analytics: "Alle Analysen anzeigen",
    role_perm_manage_folders: "Ordner verwalten",
    role_perm_invite_members: "Mitglieder einladen & entfernen",
    role_perm_apply_templates: "Firmen-Vorlagen anwenden",
    role_perm_manage_settings: "Einstellungen & Branding verwalten",
    role_perm_manage_plan: "Plan upgraden / verwalten",
    role_perm_delete_qrs: "QR Codes löschen",
    role_perm_invite_members_no: "Mitglieder einladen oder entfernen",
    role_perm_access_settings: "Zugriff auf Einstellungen & Branding",
    our_plans: "Unsere Pläne",
    // Users page
    users_title: "Benutzerverwaltung",
    users_subtitle: "Laden Sie Teammitglieder ein und verwalten Sie deren Rollen.",
    users_invite: "Benutzer einladen",
    users_invite_email: "E-Mail-Adresse",
    users_invite_role: "Rolle",
    users_invite_btn: "Einladen",
    users_invite_sending: "Wird gesendet…",
    users_invite_success: "Einladung gesendet!",
    users_invite_error: "Fehler beim Senden.",
    users_col_email: "E-Mail",
    users_col_role: "Rolle",
    users_col_joined: "Beigetreten",
    users_remove: "Entfernen",
    users_no_members: "Keine weiteren Mitglieder",
    users_resend: "Einladung erneut senden",
    users_resend_sending: "Wird gesendet…",
    users_resend_success: "Einladung erneut gesendet!",
    created_by: "Erstellt von",
    // Clients page
    clients_title: "Kunden",
    clients_subtitle: "Übersicht aller registrierten Kunden-Accounts.",
    clients_no_clients: "Noch keine Kunden registriert.",
    clients_col_qr: "QR Codes",
    clients_col_joined: "Registriert",
    clients_change_plan: "Plan ändern",
    clients_delete: "Konto löschen",
    clients_delete_confirm: "Wirklich löschen?",
    clients_stat_total: "Kunden gesamt",
    clients_plan_modal_title: "Plan wirklich ändern?",
    clients_plan_modal_stripe: "⚠️ Falls der Kunde ein aktives Stripe-Abo hat, wird dieses NICHT automatisch aktualisiert. Bitte Stripe manuell anpassen.",
    clients_plan_modal_confirm: "Ja, Plan ändern",
    clients_plan_modal_cancel: "Abbrechen",
    clients_inactive_title: "Inaktive Kunden",
    clients_inactive_body: "Diese Kunden haben in den letzten {days} Tagen keine QR Codes erstellt oder bearbeitet.",
    clients_last_active: "Zuletzt aktiv",
    clients_never_active: "Noch keine Aktivität",
    clients_view: "Anzeigen",
    clients_remind_selected: "Erinnerung senden",
    clients_remind_all: "Alle erinnern",
    clients_remind_select_all: "Alle auswählen",
    clients_remind_modal_title: "Erinnerungs-E-Mail senden",
    clients_remind_modal_hint: "Platzhalter werden pro Empfänger automatisch ersetzt: {email}, {days}, {last_active}.",
    clients_remind_subject_label: "Betreff",
    clients_remind_body_label: "Nachricht",
    clients_remind_recipients: "Empfänger",
    clients_remind_send: "Senden",
    clients_remind_send_all: "Alle senden",
    clients_remind_sending: "Wird gesendet…",
    clients_remind_sent: "Gesendet",
    clients_remind_retry: "Erneut versuchen",
    clients_remind_from: "Absender: noreply@qr-card.ch",
    clients_remind_days_inactive: "Tage inaktiv",
    clients_remind_never: "Noch nie aktiv",
    clients_remind_copy_all: "Alle Adressen kopieren",
    clients_remind_copied: "Kopiert!",
    clients_remind_close: "Schliessen",
    clients_remind_subject_default: "Wir vermissen dich bei qr-card.ch",
    clients_remind_body_default: "Hallo,\n\nwir haben bemerkt, dass du {days} Tage lang nicht in QR Platform aktiv warst (zuletzt am {last_active}).\n\nDeine QR Codes warten auf dich — logge dich ein, um neue Scans zu sehen, Inhalte zu aktualisieren oder neue QR Codes zu erstellen.\n\nBei Fragen sind wir gerne für dich da. Einfach auf diese E-Mail antworten.\n\nBis bald!",
    clients_remind_body_never: "Hallo,\n\nwir haben bemerkt, dass du dein Konto bei QR Platform noch nicht aktiv genutzt hast.\n\nMelde dich an und erstelle deinen ersten QR Code — bei Fragen antworte einfach auf diese E-Mail.\n\nBis bald!",
    clients_team_count: "Team",
    clients_role_owner_badge: "Inhaber",
    clients_via_owner: "Konto von",
    clients_no_subusers: "Keine Team-Mitglieder",
    // Client detail page
    client_detail_back: "Zurück zu Kunden",
    client_detail_profile: "Profil",
    client_detail_members: "Team-Mitglieder",
    client_detail_qrcodes: "QR Codes",
    client_detail_total_scans: "Scans gesamt",
    client_detail_joined: "Registriert",
    client_detail_last_active: "Letzte Aktivität",
    client_detail_stripe: "Stripe",
    client_detail_no_members: "Keine Team-Mitglieder",
    client_detail_no_qr: "Noch keine QR Codes",
    client_detail_active: "Aktiv",
    client_detail_paused: "Pausiert",
    client_detail_scans: "Scans",
    client_detail_role: "Rolle",
    client_detail_joined_team: "Beigetreten",
    // Paused QR page
    qr_paused_title: "QR Code pausiert",
    qr_paused_body: "Dieser QR Code ist derzeit pausiert. Der Inhaber muss seinen Plan upgraden, um ihn zu reaktivieren.",
    // Onboarding
    onboarding_title: "Willkommen! 👋",
    onboarding_subtitle: "In 3 einfachen Schritten loslegen:",
    onboarding_step1: "Erstellen Sie Ihren ersten QR Code",
    onboarding_step2: "Teilen Sie den Link oder drucken Sie den QR Code",
    onboarding_step3: "Bearbeiten Sie Ihre Daten jederzeit. Der QR Code bleibt gleich.",
    onboarding_dismiss: "Verstanden, loslegen!",
    // Scan analytics
    scans_total: "Scans gesamt",
    scans_label: "Scans",
    scans_today: "Heute",
    scans_last7: "Letzte 7 Tage",
    field_description: "Beschreibung",
    // Theme
    field_theme: "Karten-Design",
    theme_classic: "Classic",
    theme_dark: "Dark",
    theme_minimal: "Minimal",
    // Codes filter
    filter_all: "Alle",
    filter_active: "Aktiv",
    filter_paused: "Pausiert",
    qr_paused_badge: "Pausiert. Plan upgraden zum Reaktivieren.",
    sort_newest: "Neueste zuerst",
    sort_oldest: "Älteste zuerst",
    sort_name: "Name A–Z",
    export_csv: "CSV exportieren",
    contact_support: "Support kontaktieren",
    help_button: "Hilfe",
    help_title: "Plattform-Support kontaktieren",
    help_subtitle: "Senden Sie uns eine Nachricht und wir melden uns bei Ihnen.",
    help_name: "Name",
    help_name_ph: "Ihr Name",
    help_email: "E-Mail",
    help_message: "Nachricht",
    help_message_ph: "Beschreiben Sie Ihr Problem oder Ihre Frage…",
    help_send: "Nachricht senden",
    help_sending: "Wird gesendet…",
    help_send_failed: "Senden fehlgeschlagen. Bitte erneut versuchen.",
    help_sent_title: "Nachricht gesendet",
    help_sent_body: "Wir antworten Ihnen so schnell wie möglich.",
    help_close: "Schliessen",
    settings_support_email_title: "Kontakt-E-Mail",
    settings_support_email_hint: "Wird Team-Mitgliedern bei Fehlern angezeigt.",
    settings_support_email_btn: "Speichern",
    // Landing page
    landing_call: "Anrufen",
    landing_email_default: "E-Mail",
    landing_website_default: "Webseite",
    landing_document: "Dokument",
    landing_link: "Link",
    landing_save_contact: "Kontakt speichern",
    landing_share: "Teilen",
    landing_copied: "Kopiert!",
    landing_lead_btn: "Kontakt hinterlassen",
    landing_lead_title: "Kontakt hinterlassen",
    landing_lead_subtitle_suffix: "wird sich bei Ihnen melden.",
    landing_lead_thanks: "Vielen Dank!",
    landing_lead_received: "Ihre Kontaktdaten wurden empfangen.",
    landing_lead_close: "Schliessen",
    landing_lead_name: "Name",
    landing_lead_email: "E-Mail",
    landing_lead_comment: "Nachricht",
    landing_lead_optional: "(optional)",
    landing_lead_name_ph: "Ihr vollständiger Name",
    landing_lead_email_ph: "ihre@email.com",
    landing_lead_comment_ph: "Nachricht oder Notiz…",
    landing_lead_consent: "Ich willige ein, dass mein Name, E-Mail und meine Nachricht gespeichert und zur Kontaktaufnahme verwendet werden dürfen. Ich kann meine Einwilligung jederzeit widerrufen.",
    landing_lead_consent_required: "Bitte stimmen Sie der Datenverarbeitung zu, um fortzufahren.",
    landing_lead_sending: "Wird gesendet…",
    landing_lead_send: "Senden",
    landing_lead_error_generic: "Etwas ist schiefgelaufen.",
    landing_lead_error_network: "Netzwerkfehler. Bitte erneut versuchen.",
    // Dashboard page
    dashboard_title: "Dashboard",
    kpi_total_qrs: "QR Codes gesamt",
    kpi_total_scans: "Scans gesamt",
    kpi_unique_visitors: "Eindeutige Besucher",
    kpi_returning: "Wiederkehrend",
    kpi_conversion_rate: "Conversion Rate",
    dashboard_active_codes: "Aktive QR Codes",
    dashboard_paused_codes: "Pausierte QR Codes",
    chart_title: "Scans im Zeitverlauf",
    chart_subtitle: "Gesamte Scans aller QR Codes",
    chart_no_scans: "Keine Scans in diesem Zeitraum",
    recent_codes: "Neueste QR Codes",
    view_all: "Alle anzeigen",
    no_qrs_yet: "Noch keine QR Codes",
    create_first: "Ersten erstellen",
    by_label: "Von",
    interactions_title: "Interaktionen",
    interactions_subtitle: "Klick-Anzahl über alle QR Codes",
    interactions_total: "gesamt",
    no_interactions: "Noch keine Interaktionen erfasst",
    top_qrs_title: "Top QR Codes",
    top_qrs_subtitle: "Sortiert nach Scan-Anzahl",
    no_scan_data: "Noch keine Scan-Daten",
    upgrade_plan_btn: "Plan upgraden →",
    evt_phone: "Telefon",
    evt_email: "E-Mail",
    evt_website: "Webseite",
    evt_pdf: "PDF",
    evt_link: "Link",
    evt_save_contact: "Kontakt speichern",
    evt_share: "Teilen",
    evt_linkedin: "LinkedIn",
    evt_instagram: "Instagram",
    evt_facebook: "Facebook",
    evt_tiktok: "TikTok",
    evt_snapchat: "Snapchat",
    evt_x: "X",
    evt_other: "Sonstige",
    evt_lead_open: "Lead-Formular geöffnet",
    evt_lead_submit: "Lead gesendet",
    // Edit page
    edit_qr_ready: "Ihr QR Code ist bereit. Laden Sie ihn unten herunter oder passen Sie ihn an und speichern.",
    edit_basic_info: "Basisinformationen",
    edit_dest_folder: "Zielordner",
    optional: "(optional)",
    edit_qr_created_success: "QR Code erfolgreich erstellt!",
    edit_no_folder: "Kein Ordner ausgewählt",
    // Settings page (additional)
    settings_subtitle_full: "Verwalten Sie Ihr Konto und globale Plattformeinstellungen.",
    settings_account_info: "Kontoinformationen",
    settings_full_name: "Vollständiger Name",
    settings_email_label: "E-Mail-Adresse",
    settings_role_label: "Rolle:",
    settings_plan_change_short: "Ändern",
    settings_security: "Sicherheit",
    settings_2fa: "Zwei-Faktor-Authentifizierung",
    settings_2fa_hint: "Zusätzliche Login-Sicherheit über Authenticator-App",
    settings_2fa_disabled: "Vom Admin deaktiviert",
    settings_pw_confirm_label: "Passwort bestätigen",
    settings_role_member: "Mitglied",
    settings_role_owner: "Owner",
    settings_role_admin: "Admin",
    settings_your_name_ph: "Ihr Name",
    settings_pw_min_ph: "Min. 6 Zeichen",
    settings_pw_repeat_ph: "Passwort wiederholen",
    settings_update_account: "Konto aktualisieren",
    settings_2fa_enable: "Aktivieren",
    settings_2fa_active: "Aktiv",
    settings_2fa_disable: "Deaktivieren",
    settings_2fa_scan: "Mit Authenticator-App scannen (Google Authenticator, Authy, etc.)",
    settings_linked_logins: "Verknüpfte Anmeldemethoden",
    settings_linked_logins_hint: "Konten, mit denen Sie sich anmelden können",
    settings_linked_email: "E-Mail & Passwort",
    settings_linked_disconnect: "Trennen",
    settings_linked_disconnecting: "Wird getrennt …",
    settings_linked_confirm: "{provider} wirklich trennen? Sie können sich danach nicht mehr damit anmelden.",
    settings_linked_last_method: "Dies ist Ihre einzige Anmeldemethode. Legen Sie zuerst ein Passwort fest.",
    settings_linked_error: "Trennen fehlgeschlagen. Bitte erneut versuchen.",
    settings_email_needs_password: "Sie haben sich mit Google angemeldet. Bitte legen Sie zuerst ein Passwort fest, bevor Sie Ihre E-Mail ändern.",
    settings_set_password_cta: "Passwort festlegen",
    settings_email_taken: "Diese E-Mail-Adresse wird bereits verwendet.",
    settings_linked_connect_google: "Google verbinden",
    settings_linked_connect_hint: "Mit Ihrem Google-Konto schneller anmelden.",
    settings_linked_connect_error: "Verbinden fehlgeschlagen. Bitte erneut versuchen.",
    // Upgrade page
    upgrade_subscription_mgmt: "Abonnement-Verwaltung",
    upgrade_active_btn: "Aktiv",
    upgrade_stay_free: "Beim Free Plan bleiben",
    upgrade_compare_features: "Funktionen vergleichen",
    upgrade_core_feature: "Kernfunktion",
    upgrade_plan_free: "Free",
    upgrade_plan_star: "Star",
    upgrade_plan_premium: "Premium",
    upgrade_plan_platinum: "Platinum",
    cmp_qr_codes: "QR-Codes",
    cmp_qr_codes_sub: "Aktive Visitenkarten pro Konto",
    cmp_team_members: "Team-Mitglieder",
    cmp_team_members_sub: "Admins, Schreiber und Leser",
    cmp_dynamic_qr: "Dynamische QR-Codes",
    cmp_dynamic_qr_sub: "Ziel-URL jederzeit ändern",
    cmp_custom_design: "Individuelles QR-Design",
    cmp_custom_design_sub: "Logo, Farben, Formen",
    cmp_lead_capture: "Lead-Erfassung",
    cmp_lead_capture_sub: "Kontakte beim Scannen sammeln",
    cmp_analytics: "Analytics & Hot Leads",
    cmp_analytics_sub: "Scans, Geräte, Standorte",
    cmp_folders: "Ordner & Organisation",
    cmp_folders_sub: "Verschachtelte QR-Gruppen",
    cmp_bilingual: "Zweisprachige Landing (DE/EN)",
    cmp_bilingual_sub: "Automatischer Sprachschalter",
    cmp_csv_export: "CSV-Export",
    cmp_csv_export_sub: "Leads und Scans herunterladen",
    cmp_templates: "QR-Vorlagen",
    cmp_templates_sub: "Felder für das Team sperren",
    cmp_custom_domain: "Eigene Domain & White-Label",
    cmp_custom_domain_sub: "Eigene URL für QR-Karten",
    cmp_webhook: "Lead-Webhook",
    cmp_webhook_sub: "Echtzeit-Lead-Weiterleitung",
    cmp_support: "Support",
    cmp_support_sub: "Antwortzeit",
    cmp_support_community: "Community",
    cmp_support_email: "E-Mail",
    cmp_support_priority: "Priorität",
    cmp_support_dedicated: "Dediziert",
    cmp_unlimited: "Unbegrenzt",
    upgrade_hero_eyebrow_full: "Abonnement-Verwaltung",
    upgrade_hero_h: "Optimieren Sie Ihre",
    upgrade_hero_orchestration: "Orchestrierung",
    upgrade_hero_h_end: ".",
    upgrade_hero_sub: "Skalieren Sie Ihre QR-Infrastruktur mit chirurgischer Präzision. Wählen Sie das Tier, das zu Ihren Anforderungen passt.",
    upgrade_current_label: "Aktueller Plan",
    upgrade_for_individuals: "Für Einzelnutzer.",
    upgrade_for_smb: "Ideal für kleine Unternehmen.",
    upgrade_for_high_vol: "Hohe Volumen-Orchestrierung.",
    upgrade_for_enterprise: "Ultimative Enterprise-Kontrolle.",
    upgrade_per_mo: "/Monat",
    upgrade_now: "Jetzt upgraden",
    // Leads
    leads_title: "Leads",
    leads_subtitle: "Kontakte, die über Ihre QR-Karten eingereicht wurden",
    leads_search_ph: "Suche nach Name, E-Mail oder QR-Karte…",
    leads_all_members: "Alle Mitglieder",
    leads_none_search: "Keine Leads für diese Suche",
    leads_none: "Noch keine Leads",
    leads_none_hint: "Aktivieren Sie Lead Capture auf einer QR-Karte, um Kontakte zu sammeln.",
    leads_count_one: "Lead",
    leads_count_many: "Leads",
    leads_open_live: "Live-Karte öffnen",
    leads_edit: "Bearbeiten",
    leads_analytics: "Analyse",
    leads_preview_qr: "QR Code Vorschau",
    leads_edit_card: "QR-Karte bearbeiten",
    leads_qr_card: "QR Karte",
    // Folders
    folders_title: "Ordner",
    folders_total_suffix: "Ordner insgesamt",
    folders_load_error: "Fehler beim Laden",
    folders_name_ph: "Ordnername",
    folders_save: "Speichern",
    folders_create: "Erstellen",
    folders_move: "Ordner verschieben",
    folders_move_for: "Neues Verzeichnis für",
    folders_root_option: "— Root (kein übergeordneter Ordner)",
    folders_moving: "Verschieben...",
    folders_move_btn: "Verschieben",
    folders_subfolder: "Unterordner",
    folders_rename: "Umbenennen",
    folders_delete: "Löschen",
    folders_delete_q: "Ordner löschen?",
    folders_delete_body: "wird unwiderruflich gelöscht.",
    folders_delete_move_title: "Inhalte werden verschoben:",
    folders_delete_move_qrs: "QR-Karte(n) werden verschoben",
    folders_delete_move_users: "Team-Mitglied(er) werden verschoben",
    folders_delete_move_subfolders: "Unterordner werden verschoben",
    folders_delete_move_to_parent: "in den übergeordneten Ordner",
    folders_delete_move_to_root: "in den Hauptbereich (kein Ordner)",
    folders_structure: "Struktur",
    folders_click_to_open: "Klicken zum Öffnen",
    folders_none: "Noch keine Ordner",
    folders_none_hint: "Ordner werden automatisch erstellt.",
    folders_select: "Ordner auswählen",
    folders_select_hint: "Klicken Sie links auf einen Ordner um dessen Inhalt zu sehen.",
    folders_no_qr: "Keine QR-Codes in diesem Ordner",
    folders_assign_qr: "QR-Codes zuweisen",
    folders_yes_delete: "Ja, löschen",
    folders_cancel: "Abbrechen",
    folders_no_name: "(kein Name)",
    folders_edit_title: "Bearbeiten",
    folders_open_title: "Öffnen",
    folders_move_to_folder: "In Ordner verschieben",
    folders_remove_from: "Aus Ordner entfernen",
    folders_qr_codes_label: "QR-Codes",
    folders_users_label: "Nutzer",
    folders_all_qr: "Alle QR-Codes",
    folders_generic_error: "Fehler",
    // Clients (additional)
    clients_email: "E-Mail",
    clients_plan: "Plan",
    clients_label: "Beschriftung",
    clients_status: "Status",
    clients_manual: "Manuell",
    clients_from: "Von",
    clients_to: "Bis",
    clients_not_found: "Kunde nicht gefunden.",
    sign_out: "Abmelden",
    signing_out: "Wird abgemeldet…",
    // Public homepage
    home_signin: "Anmelden",
    home_start_free: "Kostenlos starten",
    home_eyebrow: "Digitale Visitenkarten leicht gemacht",
    home_hero_h1_a: "Ihr QR-Code.",
    home_hero_h1_b: "Immer aktuell.",
    home_hero_sub: "Erstellen Sie in Sekunden eine digitale Visitenkarte mit QR-Code. Kontaktdaten, Logo, Social Media. Jederzeit bearbeitbar, ohne neuen Druck.",
    home_trust_no_app: "Kein App-Download",
    home_trust_free: "Kostenlos starten",
    home_trust_cancel: "Jederzeit kündbar",
    home_card_role: "Geschäftsführer · Muster AG",
    home_phone_company_line1: "MUSTER",
    home_phone_company_line2: "BAU GMBH",
    home_phone_name: "Max Mustermann",
    home_phone_role: "Bauleiter",
    home_phone_save: "Kontakt speichern",
    home_ideal_label: "Ideal für:",
    home_ideal1: "Vertrieb & Aussendienst",
    home_ideal2: "Baustelle & Service",
    home_ideal3: "Netzwerk & Events",
    home_features_title: `Warum ${BRAND_NAME}?`,
    home_feat1_title: "Digitale Visitenkarten",
    home_feat1_desc: "Erstellen Sie professionelle QR-Codes mit Kontaktdaten, Logo, Social Media und mehr.",
    home_feat2_title: "Überall zugänglich",
    home_feat2_desc: "Ihre QR-Codes sind jederzeit und von überall abrufbar, ohne App-Download.",
    home_feat3_title: "Sicher & zuverlässig",
    home_feat3_desc: "Ihre Daten werden sicher gespeichert und sind nur für Sie verwaltbar.",
    home_how_title: "So funktioniert's",
    home_how_sub: "In 3 einfachen Schritten zur digitalen Visitenkarte.",
    home_step1_title: "QR-Code erstellen",
    home_step1_desc: "Tragen Sie Ihre Kontaktdaten, Logo und Social-Media-Links ein. In wenigen Sekunden ist Ihr QR-Code fertig.",
    home_step2_title: "Drucken oder teilen",
    home_step2_desc: "Laden Sie Ihren QR-Code als PNG herunter und drucken ihn auf Visitenkarten, Flyer oder wohin Sie möchten.",
    home_step3_title: "Jederzeit bearbeiten",
    home_step3_desc: "Ändern Sie Ihre Daten wann immer Sie wollen. Der gedruckte QR-Code leitet immer auf die aktuellen Infos weiter.",
    home_demo_title: "Probieren Sie es aus",
    home_demo_sub: "Geben Sie Ihren Namen ein und sehen Sie Ihren QR-Code live.",
    home_demo_name: "Ihr Name",
    home_demo_company: "Firma",
    home_demo_create: "Eigenen Code erstellen →",
    home_use_title: "Wo können Sie ihn einsetzen?",
    home_use_sub: "Überall dort, wo Sie gefunden werden möchten.",
    home_use1_title: "Visitenkarte",
    home_use1_desc: "Drucken Sie Ihren QR-Code auf Ihre Visitenkarte. Ein Scan und alle Infos sind direkt im Handy.",
    home_use2_title: "Flyer & Plakate",
    home_use2_desc: "Ergänzen Sie Flyer, Plakate oder Broschüren mit Ihrem QR-Code für sofortigen Kontakt.",
    home_use3_title: "Türschild / Eingang",
    home_use3_desc: "Befestigen Sie einen QR-Code am Eingang. Besucher speichern Ihre Daten direkt beim Ankommen.",
    home_pricing_title: "Einfache Preisgestaltung",
    home_pricing_sub: "Starten Sie kostenlos. Upgraden Sie wenn Sie bereit sind.",
    home_pricing_popular: "Beliebteste",
    home_pricing_per_month: "/Monat",
    home_pricing_no_expiry: "Kein Ablauf",
    home_cta_free: "Kostenlos starten",
    home_cta_star: "Star wählen",
    home_cta_premium: "Premium wählen",
    home_cta_platinum: "Platinum wählen",
    home_cta_select_suffix: "wählen",
    home_faq_title: "Häufige Fragen",
    home_faq_sub: "Alles was Sie wissen müssen, kurz und klar.",
    home_faq1_q: "Was ist ein dynamischer QR-Code?",
    home_faq1_a: "Ein dynamischer QR-Code leitet auf eine URL weiter, die Sie jederzeit ändern können, ohne den gedruckten QR-Code zu ersetzen. Ihre Kunden scannen immer die aktuellsten Daten.",
    home_faq2_q: "Kann ich meinen QR-Code nach dem Drucken noch bearbeiten?",
    home_faq2_a: "Ja! Das ist der grösste Vorteil unserer Plattform. Sie können Name, Kontaktdaten, Logo, Social-Media-Links und mehr jederzeit aktualisieren. Der QR-Code selbst bleibt unverändert.",
    home_faq3_q: "Brauchen meine Kunden eine App zum Scannen?",
    home_faq3_a: "Nein. Jedes moderne Smartphone kann QR-Codes direkt mit der Kamera-App scannen, ganz ohne App-Download.",
    home_faq4_q: "Wie lade ich meinen QR-Code herunter?",
    home_faq4_a: "Nach dem Erstellen können Sie Ihren QR-Code als PNG-Datei herunterladen und direkt auf Visitenkarten, Flyer oder Ihr Material drucken.",
    home_faq5_q: "Kann ich sehen, wie oft mein QR-Code gescannt wurde?",
    home_faq5_a: "Ja. Im Dashboard sehen Sie für jeden QR-Code die Scan-Statistiken: wann und wie oft gescannt wurde.",
    home_faq6_q: "Was passiert, wenn ich mein Abo kündige?",
    home_faq6_a: "Ihre QR-Codes bleiben aktiv. Sie können jedoch keine neuen Codes mehr erstellen und haben keinen Zugriff auf Premium-Funktionen, bis Sie wieder upgraden.",
    home_faq7_q: "Kann ich mein eigenes Logo im QR-Code einbetten?",
    home_faq7_a: "Ja. Ab dem Star-Plan können Sie Ihr Logo in die Mitte des QR-Codes einbetten, für einen professionellen, markentreuen Auftritt.",
    home_footer_about: "Digitale Visitenkarten mit QR-Code. Einmal erstellen, jederzeit aktualisieren. Kein Neudruck nötig.",
    home_footer_platform: "Plattform",
    home_footer_pricing: "Preise",
    home_footer_faq: "FAQ",
    home_footer_start: "Jetzt starten",
    home_footer_start_desc: "Erstellen Sie Ihren ersten QR-Code kostenlos, in weniger als 2 Minuten.",
    home_footer_register: "Kostenlos registrieren",
    home_footer_rights: "Alle Rechte vorbehalten.",
    home_footer_made_in: "Made in Switzerland 🇨🇭",
    // Sidebar (additional)
    nav_leads: "Leads",
    sidebar_enterprise: "Enterprise Suite",
    sidebar_create_qr: "QR Code erstellen",
    // Settings - company / branding
    settings_company_info: "Unternehmen",
    settings_company_subtitle: "Unternehmensdaten und Kontakt — bearbeitbar durch Admins, nutzbar in Vorlagen",
    settings_brand_name: "Markenname",
    settings_brand_logo: "Logo",
    settings_brand_color: "Markenfarbe",
    settings_company_address: "Adresse",
    settings_company_phone: "Telefon",
    settings_company_email: "E-Mail",
    settings_company_website: "Webseite",
    settings_save: "Speichern",
    settings_saved: "Gespeichert!",
    settings_org_name: "Organisationsname",
    settings_org_name_ph: "Name Ihrer Organisation",
    settings_contact_info: "Kontaktinfo",
    settings_phone_ph: "+41 00 000 00 00",
    settings_email_ph: "info@unternehmen.ch",
    settings_website_ph: "www.unternehmen.ch",
    settings_social_media: "Social Media",
    settings_address: "Adresse",
    settings_street_ph: "Strasse",
    settings_streetnr_ph: "Nr.",
    settings_plz_ph: "PLZ",
    settings_city_ph: "Ort",
    settings_country_ph: "Land",
    settings_save_company: "Unternehmensdaten speichern",
    settings_saving: "Wird gespeichert…",
    settings_saved_short: "Gespeichert",
    settings_platform_prefs: "Plattform-Einstellungen",
    settings_regional: "Regional",
    settings_language: "Sprache",
    settings_timezone: "Zeitzone",
    settings_features: "Funktionen",
    settings_lead_capture: "Lead Capture",
    settings_lead_capture_hint: "Standard für neue QR-Codes. Bestehende QR-Codes und ihre bisherigen Leads bleiben unverändert — nur neu erstellte QR-Codes folgen dieser Einstellung.",
    // Codes page
    codes_page_title: "QR Codes",
    codes_page_subtitle: "Verwalten und überwachen Sie Ihre Enterprise QR-Infrastruktur.",
    codes_recent: "Neueste QR Codes",
    codes_search_label: "Suche",
    codes_filter_label: "Filter",
    codes_sort_label: "Sortierung",
    codes_folder_label: "Ordner",
    codes_folder_all: "Alle Ordner",
    codes_folder_none: "Ohne Ordner",
    codes_export_folder: "Ordner exportieren",
    codes_export_csv: "CSV Export",
    codes_back_to_codes: "QR Codes",
    codes_new_folder: "Neuer Ordner",
    codes_subfolder_ph: "Unterordner-Name",
    codes_folder_ph: "Ordner-Name",
    codes_create_folder_btn: "Erstellen",
    codes_folders_section: "ORDNER",
    codes_view_all_folders: "Alle Ordner anzeigen",
    codes_qr_singular: "QR Code",
    codes_qr_plural: "QR Codes",
    codes_pause_folder: "Alle QR-Codes im Ordner pausieren",
    codes_activate_folder: "Alle QR-Codes im Ordner aktivieren",
    codes_drag_remove: "Hierher ziehen um aus Ordner zu entfernen",
    codes_qrs_in_folder_prefix: "QR-CODES IN",
    codes_recent_section: "NICHT ZUGEORDNET",
    codes_all_members: "Alle Mitglieder",
    codes_created_by_team: "Erstellt von",
    codes_delete_folder: "Ordner löschen",
    codes_delete_folder_title: "Ordner löschen",
    codes_delete_folder_subtitle: "Was möchten Sie mit den enthaltenen QR-Codes tun?",
    codes_delete_folder_move: "QR-Codes behalten",
    codes_delete_folder_move_desc: "QR-Codes nach \"Nicht zugeordnet\" verschieben und Ordner (inkl. Unterordner) löschen.",
    codes_delete_folder_purge: "Alles löschen",
    codes_delete_folder_purge_desc: "Ordner, alle Unterordner und alle enthaltenen QR-Codes endgültig löschen.",
    codes_delete_folder_cancel: "Abbrechen",
    codes_delete_all_btn: "Alle QR-Codes löschen",
    codes_delete_all_root_title: "Alle QR-Codes löschen?",
    codes_delete_all_root_body: "Dadurch werden ALLE QR-Codes in Ihrer Organisation endgültig gelöscht – auch jene in Ordnern und Unterordnern. Die Ordner selbst bleiben bestehen.",
    codes_delete_all_folder_title: "Alle QR-Codes in diesem Ordner löschen?",
    codes_delete_all_folder_body: "Dadurch werden alle QR-Codes in diesem Ordner und allen Unterordnern endgültig gelöscht. Die Ordner selbst bleiben bestehen.",
    codes_delete_all_count: "Betroffen:",
    codes_delete_all_confirm: "Endgültig löschen",
    codes_delete_all_cancel: "Abbrechen",
    codes_folder_tree_close: "Schliessen",
    codes_departed_members: "Nur ehemalige Mitglieder",
    codes_departed_divider: "──────────",
    departed_badge_tooltip: "Klicken für Verlauf",
    departed_modal_title: "Erstellt von ehemaligem Mitglied",
    departed_modal_subtitle: "Diese QR-Karte wurde von einem Benutzer erstellt, der die Organisation verlassen hat. Die Karte bleibt unter dem Admin-Konto bestehen.",
    departed_modal_creator: "Ursprünglicher Ersteller",
    departed_modal_role: "Rolle",
    departed_modal_card_created: "QR-Karte erstellt am",
    departed_modal_left: "Konto gelöscht am",
    departed_modal_unknown: "Unbekannt",
    departed_modal_close: "Schliessen",
    // Users page
    users_team_access: "Team-Zugriff",
    users_team_subtitle: "Organisieren Sie Ihre Enterprise-Hierarchie. Verwalten Sie Berechtigungen, laden Sie Stakeholder ein und steuern Sie das organisatorische Wachstum von einer zentralen Stelle aus.",
    users_export_list: "Liste exportieren",
    users_invite_member: "Mitglied einladen",
    users_stat_total: "Benutzer gesamt",
    users_stat_admins: "Admins",
    users_stat_pending: "Offene Einladungen",
    users_table_title: "Aktuelle Team-Mitglieder",
    users_col_user: "Benutzer-Details",
    users_col_access: "Zugriffslevel",
    users_col_status: "Status",
    users_col_join: "Beitrittsdatum",
    users_col_actions: "Aktionen",
  },
  en: {
    // Sidebar
    nav_dashboard: "Dashboard",
    nav_codes: "QR Codes",
    branding_color_clear: "Clear color",
    nav_analytics: "Analytics",
    analytics_overview_title: "Analytics Overview",
    analytics_overview_subtitle: "Performance of your QR codes at a glance",
    analytics_col_code: "QR Code",
    analytics_col_total: "Total scans",
    analytics_col_7d: "Last 7 days",
    analytics_col_unique: "Unique visitors",
    analytics_col_leads: "Leads",
    analytics_col_conversion: "Conversion",
    analytics_col_last_scan: "Last scan",
    analytics_empty: "No QR codes yet — once you create one, stats will appear here.",
    analytics_loading: "Loading…",
    analytics_never: "Never",
    nav_settings: "Settings",
    nav_users: "Users",
    nav_clients: "Clients",
    nav_plans: "Plans",
    nav_trash: "Trash",
    nav_plan_settings: "Plan Settings",
    nav_language: "Language",
    plan_settings_title: "Plan Settings",
    plan_settings_subtitle: "Edit prices and features for each plan.",
    plan_settings_price: "Price (CHF/month)",
    plan_settings_features: "Features (max. 4)",
    plan_settings_feature_placeholder: "e.g. Unlimited QR Codes",
    plan_settings_save: "Save",
    plan_settings_saved: "Saved!",
    plan_settings_edit: "Edit",
    plan_settings_cancel: "Cancel",
    plan_settings_stripe_warning: "⚠️ Price changes are NOT automatically applied in Stripe. Please also update the price manually in the Stripe Dashboard.",
    plan_settings_stripe_banner_title: "Stripe prices must stay in sync",
    plan_settings_stripe_banner_body: "If you change a plan price here, you must also update the matching product price in your Stripe dashboard. Mismatched prices will cause checkout and billing conflicts — customers may be charged a different amount than what they see on the site.",
    plan_settings_stripe_banner_link: "Open Stripe products dashboard →",
    plan_settings_stripe_confirm: "Understood, save anyway",
    plan_settings_stripe_title: "Update Stripe manually",
    plan_settings_stripe_body: "Prices here and in Stripe are not linked. Changing the price here only updates the display. Stripe stays unchanged.",
    plan_settings_stripe_steps: "After saving, please in Stripe:",
    plan_settings_stripe_step1: "Create a new price for the product",
    plan_settings_stripe_step2: "Archive the old price",
    plan_settings_stripe_step3: "Update the new Price ID in the code",
    logout: "Logout",
    // Dashboard page
    dashboard_subtitle: "Manage your QR codes",
    create_qr: "Create QR Code",
    stat_total: "Total QR Codes",
    stat_active: "Active",
    stat_paused: "Paused",
    stat_phone: "With Phone",
    stat_website: "With Website",
    all_codes: "All QR Codes",
    no_codes: "No QR codes yet",
    no_codes_sub: "Create your first QR code",
    create_now: "Create now",
    col_name: "Name / Company",
    col_created: "Created",
    col_link: "Link",
    col_actions: "Actions",
    col_created_by: "Created by",
    delete_confirm: "Click again to confirm",
    delete: "Delete",
    // Codes page
    new_qr: "New QR Code",
    search_placeholder: "Search by name, company or ID...",
    no_results: "No QR codes found",
    unnamed: "Unnamed",
    edit: "Edit",
    codes_total: "QR Codes total",
    // Settings
    settings_title: "Settings",
    settings_subtitle: "Platform Settings",
    settings_placeholder: "Settings will be available in a future version.",
    settings_account: "Account",
    settings_plan_change: "Change plan",
    settings_email_change: "Change Email",
    settings_email_current: "Current Email",
    settings_email_new: "New Email Address",
    settings_email_saving: "Saving...",
    settings_email_btn: "Change Email",
    settings_email_error_same: "Please enter a different email address.",
    settings_email_success: "Confirmation email sent to the new address. Please check your inbox and click the link to complete the change.",
    settings_account_saved: "Changes saved.",
    settings_pw_change: "Change Password",
    settings_pw_current: "Current Password",
    settings_pw_new: "New Password",
    settings_pw_confirm: "Confirm New Password",
    settings_pw_saving: "Saving...",
    settings_pw_btn: "Change Password",
    settings_pw_error_match: "Passwords do not match.",
    settings_pw_error_short: "Minimum 6 characters required.",
    settings_pw_error_wrong: "Current password is incorrect.",
    settings_pw_success: "Password changed successfully.",
    // Create page
    create_title: "New QR Code",
    create_subtitle: "Fill in the fields and create your QR code",
    create_error: "Error creating. Please try again.",
    create_submit: "Create QR Code",
    // Edit page
    edit_title: "Edit QR Code",
    edit_success: "QR code successfully created!",
    saved: "Saved!",
    save_error: "Error saving.",
    open_page: "Open page",
    copy_link: "Copy link",
    copied: "Copied!",
    download_qr: "Download QR",
    save: "Save",
    // QRForm
    qr_label: "QR Code Name",
    qr_label_hint: "Only visible to you – helps identify it in the dashboard.",
    qr_label_placeholder: "e.g. Trade Fair 2025, Office Card",
    section_identity: "Identity",
    section_contact: "Contact Details",
    section_social: "Social Media",
    section_pdf: "File / PDF",
    section_notes: "Notes (internal) - only visible in the dashboard",
    field_first_name: "First Name",
    field_last_name: "Last Name",
    field_title: "Title / Position",
    field_company: "Company",
    field_logo: "Logo",
    field_logo_hint: "Direct image link (PNG, JPG, SVG)",
    upload_remove: "Remove",
    upload_uploading: "Uploading…",
    upload_error_size: "File too large. Maximum 14 MB.",
    upload_error_failed: "Upload failed. Please try again.",
    upload_logo: "Upload logo",
    upload_logo_hint: "Max. 14 MB · Automatically compressed if needed",
    upload_pdf: "Upload PDF",
    upload_pdf_open: "Open current file",
    upload_pdf_hint: "Max. 14 MB · PDF files only",
    pdf_option_upload: "Upload file",
    pdf_option_link: "Add link",
    link_label_placeholder: "e.g. Brochure, Price list…",
    link_add: "Add",
    links_max: "Maximum 4 entries reached",
    field_color: "Accent Color",
    field_color_hint: "Used as the background color on your QR business card.",
    upload_bg: "Upload Background Image",
    upload_bg_hint: "Max. 14 MB · If empty, the accent color is used.",
    field_phone: "Phone",
    field_email: "Email",
    field_website: "Website",
    field_street: "Street",
    field_street_nr: "No.",
    field_plz: "Postal Code",
    field_city: "City",
    field_linkedin: "LinkedIn URL",
    field_instagram: "Instagram URL",
    field_facebook: "Facebook URL",
    field_tiktok: "TikTok URL",
    field_snapchat: "Snapchat URL",
    field_x: "X (Twitter) URL",
    field_other_social: "Other (URL)",
    field_pdf_url: "PDF / File URL",
    field_pdf_label: "Button Label",
    field_notes: "Internal Note",
    field_notes_placeholder: "Only visible in the dashboard...",
    cancel: "Cancel",
    // Plan
    plan_label: "Plan",
    plan_limit_reached: "Limit reached for plan",
    plan_upgrade_hint: "Please upgrade your plan.",
    free_plan_banner: "You're on the Free plan. Limited to 1 QR code.",
    free_plan_upgrade: "Upgrade now →",
    plan_limit_ask_owner: "Ask the account owner to upgrade the plan",
    see_plans: "See Plans",
    // Upgrade page
    upgrade_title: "Upgrade Plan",
    upgrade_subtitle: "Choose the right plan for your needs",
    upgrade_current: "Current",
    upgrade_per_month: "/month",
    upgrade_current_plan: "Your current plan",
    upgrade_loading: "Loading…",
    upgrade_select: "Select",
    upgrade_no_expiry: "No expiry",
    upgrade_unlimited: "Unlimited",
    // Social placeholders
    social_placeholder: "username",
    qr_logo_in_center: "Show logo in QR code",
    delete_modal_title: "Delete QR Code?",
    delete_modal_body: "All data for this QR code will be permanently deleted. This action cannot be undone.",
    delete_modal_cancel: "Cancel",
    pause_modal_pause_folder: "Pause entire folder?",
    pause_modal_pause_qr: "Pause this QR Code?",
    pause_modal_activate_folder: "Activate entire folder?",
    pause_modal_activate_qr: "Activate this QR Code?",
    pause_modal_pause_body: "Anyone who scans this QR code will be redirected to qr-card.ch instead of your contact page.",
    pause_modal_pause_body_folder: "Anyone who scans any QR code from this folder will be redirected to qr-card.ch instead of QR card link.",
    pause_modal_activate_body: "The QR code will become active again and visitors will see your contact page.",
    pause_modal_activate_body_folder: "All QR codes in this folder will become active again, and visitors will be redirected to the corresponding QR card link.",
    pause_modal_redirect_note_prefix: "Paused QR codes redirect to",
    pause_modal_cancel: "Cancel",
    pause_modal_confirm_pause: "Yes, Pause",
    pause_modal_confirm_activate: "Yes, Activate",
    delete_modal_confirm: "Yes, delete",
    // Roles
    role_admin: "Admin",
    role_writer: "Editor",
    role_owner: "Owner",
    role_label: "Role",
    our_plans: "Our Plans",
    // Role permissions card
    role_perm_title: "Role Permissions",
    role_perm_subtitle: "What each role can do on the platform.",
    role_perm_owner_subtitle: "Account holder",
    role_perm_admin_subtitle: "Team manager",
    role_perm_writer_subtitle: "Content editor",
    role_perm_create_edit_delete: "Create, edit & delete QR codes",
    role_perm_create_edit_delete_restore: "Create, edit & delete QR codes, with restore available for 72 hours",
    role_perm_create_edit: "Create & edit QR codes",
    role_perm_view_analytics: "View all analytics",
    role_perm_manage_folders: "Manage folders",
    role_perm_invite_members: "Invite & remove members",
    role_perm_apply_templates: "Apply company templates",
    role_perm_manage_settings: "Manage settings & branding",
    role_perm_manage_plan: "Upgrade / manage plan",
    role_perm_delete_qrs: "Delete QR codes",
    role_perm_invite_members_no: "Invite or remove members",
    role_perm_access_settings: "Access settings & branding",
    // Users page
    users_title: "User Management",
    users_subtitle: "Invite team members and manage their roles.",
    users_invite: "Invite User",
    users_invite_email: "Email Address",
    users_invite_role: "Role",
    users_invite_btn: "Invite",
    users_invite_sending: "Sending…",
    users_invite_success: "Invitation sent!",
    users_invite_error: "Error sending invite.",
    users_col_email: "Email",
    users_col_role: "Role",
    users_col_joined: "Joined",
    users_remove: "Remove",
    users_no_members: "No other members",
    users_resend: "Resend invitation",
    users_resend_sending: "Sending…",
    users_resend_success: "Invitation resent!",
    created_by: "Created by",
    // Clients page
    clients_title: "Clients",
    clients_subtitle: "Overview of all registered client accounts.",
    clients_no_clients: "No clients registered yet.",
    clients_col_qr: "QR Codes",
    clients_col_joined: "Registered",
    clients_change_plan: "Change plan",
    clients_delete: "Delete account",
    clients_delete_confirm: "Really delete?",
    clients_stat_total: "Total clients",
    clients_plan_modal_title: "Really change plan?",
    clients_plan_modal_stripe: "⚠️ If this client has an active Stripe subscription, it will NOT be updated automatically. Please update Stripe manually.",
    clients_plan_modal_confirm: "Yes, change plan",
    clients_plan_modal_cancel: "Cancel",
    clients_inactive_title: "Inactive clients",
    clients_inactive_body: "These clients have not created or updated any QR codes in the last {days} days.",
    clients_last_active: "Last active",
    clients_never_active: "No activity yet",
    clients_view: "View",
    clients_remind_selected: "Send reminder",
    clients_remind_all: "Remind all",
    clients_remind_select_all: "Select all",
    clients_remind_modal_title: "Send reminder email",
    clients_remind_modal_hint: "Placeholders are replaced per recipient: {email}, {days}, {last_active}.",
    clients_remind_subject_label: "Subject",
    clients_remind_body_label: "Message",
    clients_remind_recipients: "Recipients",
    clients_remind_open_email: "Open email",
    clients_remind_send: "Send",
    clients_remind_send_all: "Send all",
    clients_remind_sending: "Sending…",
    clients_remind_sent: "Sent",
    clients_remind_retry: "Retry",
    clients_remind_from: "From: noreply@qr-card.ch",
    clients_remind_days_inactive: "days inactive",
    clients_remind_never: "Never active",
    clients_remind_copy_all: "Copy all addresses",
    clients_remind_copied: "Copied!",
    clients_remind_close: "Close",
    clients_remind_subject_default: "We miss you at qr-card.ch",
    clients_remind_body_default: "Hi,\n\nwe noticed you haven't been active on QR Platform for {days} days (last seen {last_active}).\n\nYour QR codes are waiting for you — sign in to check new scans, update content, or build new codes.\n\nIf anything's in the way, just reply to this email and we'll help.\n\nSee you soon!",
    clients_remind_body_never: "Hi,\n\nwe noticed you haven't used your QR Platform account yet.\n\nSign in and create your first QR code — if anything's in the way, just reply to this email.\n\nSee you soon!",
    clients_team_count: "Team",
    clients_role_owner_badge: "Owner",
    clients_via_owner: "Account of",
    clients_no_subusers: "No team members",
    // Client detail page
    client_detail_back: "Back to clients",
    client_detail_profile: "Profile",
    client_detail_members: "Team members",
    client_detail_qrcodes: "QR Codes",
    client_detail_total_scans: "Total scans",
    client_detail_joined: "Registered",
    client_detail_last_active: "Last activity",
    client_detail_stripe: "Stripe",
    client_detail_no_members: "No team members",
    client_detail_no_qr: "No QR codes yet",
    client_detail_active: "Active",
    client_detail_paused: "Paused",
    client_detail_scans: "Scans",
    client_detail_role: "Role",
    client_detail_joined_team: "Joined",
    // Paused QR page
    qr_paused_title: "QR Code paused",
    qr_paused_body: "This QR code is currently paused. The owner needs to upgrade their plan to reactivate it.",
    // Onboarding
    onboarding_title: "Welcome! 👋",
    onboarding_subtitle: "Get started in 3 simple steps:",
    onboarding_step1: "Create your first QR code",
    onboarding_step2: "Share the link or print the QR code",
    onboarding_step3: "Edit your details anytime. The QR code stays the same.",
    onboarding_dismiss: "Got it, let's go!",
    // Scan analytics
    scans_total: "Total scans",
    scans_label: "Scans",
    scans_today: "Today",
    scans_last7: "Last 7 days",
    field_description: "Description",
    // Theme
    field_theme: "Card Design",
    theme_classic: "Classic",
    theme_dark: "Dark",
    theme_minimal: "Minimal",
    // Codes filter
    filter_all: "All",
    filter_active: "Active",
    filter_paused: "Paused",
    qr_paused_badge: "Paused. Upgrade plan to reactivate.",
    sort_newest: "Newest first",
    sort_oldest: "Oldest first",
    sort_name: "Name A–Z",
    export_csv: "Export CSV",
    contact_support: "Contact support",
    help_button: "Help",
    help_title: "Contact platform support",
    help_subtitle: "Send us a message and we'll get back to you.",
    help_name: "Name",
    help_name_ph: "Your name",
    help_email: "Email",
    help_message: "Message",
    help_message_ph: "Describe your issue or question…",
    help_send: "Send message",
    help_sending: "Sending…",
    help_send_failed: "Send failed. Please try again.",
    help_sent_title: "Message sent",
    help_sent_body: "We'll get back to you as soon as we can.",
    help_close: "Close",
    settings_support_email_title: "Contact Email",
    settings_support_email_hint: "Shown to team members when a save error occurs.",
    settings_support_email_btn: "Save",
    // Landing page
    landing_call: "Call",
    landing_email_default: "Email",
    landing_website_default: "Website",
    landing_document: "Document",
    landing_link: "Link",
    landing_save_contact: "Save contact",
    landing_share: "Share",
    landing_copied: "Copied!",
    landing_lead_btn: "Leave your contact",
    landing_lead_title: "Leave your contact",
    landing_lead_subtitle_suffix: "will be in touch.",
    landing_lead_thanks: "Thank you!",
    landing_lead_received: "Your contact has been received.",
    landing_lead_close: "Close",
    landing_lead_name: "Name",
    landing_lead_email: "Email",
    landing_lead_comment: "Comment",
    landing_lead_optional: "(optional)",
    landing_lead_name_ph: "Your full name",
    landing_lead_email_ph: "your@email.com",
    landing_lead_comment_ph: "Any message or note…",
    landing_lead_consent: "I agree that my name, email and message may be stored and used to contact me. I can withdraw my consent at any time.",
    landing_lead_consent_required: "Please tick the consent checkbox to continue.",
    landing_lead_sending: "Sending…",
    landing_lead_send: "Send contact",
    landing_lead_error_generic: "Something went wrong.",
    landing_lead_error_network: "Network error. Please try again.",
    // Dashboard page
    dashboard_title: "Dashboard",
    kpi_total_qrs: "Total QR Codes",
    kpi_total_scans: "Total Scans",
    kpi_unique_visitors: "Unique Visitors",
    kpi_returning: "Returning",
    kpi_conversion_rate: "Conversion Rate",
    dashboard_active_codes: "Active QR Codes",
    dashboard_paused_codes: "Paused QR Codes",
    chart_title: "Scans Over Time",
    chart_subtitle: "Total scans across all QR codes",
    chart_no_scans: "No scans in this period",
    recent_codes: "Recent QR Codes",
    view_all: "View all",
    no_qrs_yet: "No QR codes yet",
    create_first: "Create first",
    by_label: "By",
    interactions_title: "Interactions",
    interactions_subtitle: "Click counts across all QR codes",
    interactions_total: "total",
    no_interactions: "No interactions tracked yet",
    top_qrs_title: "Top Performing QR Codes",
    top_qrs_subtitle: "Ranked by total scan count",
    no_scan_data: "No scan data yet",
    upgrade_plan_btn: "Upgrade Plan →",
    evt_phone: "Phone",
    evt_email: "Email",
    evt_website: "Website",
    evt_pdf: "PDF",
    evt_link: "Link",
    evt_save_contact: "Save Contact",
    evt_share: "Share",
    evt_linkedin: "LinkedIn",
    evt_instagram: "Instagram",
    evt_facebook: "Facebook",
    evt_tiktok: "TikTok",
    evt_snapchat: "Snapchat",
    evt_x: "X",
    evt_other: "Other",
    evt_lead_open: "Lead Form Opened",
    evt_lead_submit: "Lead Submitted",
    // Edit page
    edit_qr_ready: "Your QR code is ready. Download it below or make any adjustments and save.",
    edit_basic_info: "Basic Information",
    edit_dest_folder: "Destination Folder",
    optional: "(optional)",
    edit_qr_created_success: "QR Code created successfully!",
    edit_no_folder: "No folder selected",
    // Settings page (additional)
    settings_subtitle_full: "Manage your account orchestration and global platform preferences.",
    settings_account_info: "Account Information",
    settings_full_name: "Full Name",
    settings_email_label: "Email Address",
    settings_role_label: "Role:",
    settings_plan_change_short: "Change",
    settings_security: "Security",
    settings_2fa: "Two-Factor Auth",
    settings_2fa_hint: "Extra login security via authenticator app",
    settings_2fa_disabled: "Disabled by admin",
    settings_pw_confirm_label: "Confirm Password",
    settings_role_member: "Member",
    settings_role_owner: "Owner",
    settings_role_admin: "Admin",
    settings_your_name_ph: "Your name",
    settings_pw_min_ph: "Min. 6 characters",
    settings_pw_repeat_ph: "Repeat password",
    settings_update_account: "Update Account",
    settings_2fa_enable: "Enable",
    settings_2fa_active: "Active",
    settings_2fa_disable: "Disable",
    settings_2fa_scan: "Scan with your authenticator app (Google Authenticator, Authy, etc.)",
    settings_linked_logins: "Linked sign-in methods",
    settings_linked_logins_hint: "Accounts you can use to sign in",
    settings_linked_email: "Email & password",
    settings_linked_disconnect: "Disconnect",
    settings_linked_disconnecting: "Disconnecting…",
    settings_linked_confirm: "Disconnect {provider}? You won't be able to sign in with it after this.",
    settings_linked_last_method: "This is your only sign-in method. Set a password first.",
    settings_linked_error: "Could not disconnect. Please try again.",
    settings_email_needs_password: "You signed up with Google. Please set a password before changing your email.",
    settings_set_password_cta: "Set password",
    settings_email_taken: "This email address is already in use.",
    settings_linked_connect_google: "Connect Google",
    settings_linked_connect_hint: "Use your Google account to sign in faster.",
    settings_linked_connect_error: "Could not connect. Please try again.",
    // Upgrade page
    upgrade_subscription_mgmt: "Subscription Management",
    upgrade_active_btn: "Active",
    upgrade_stay_free: "Stay on Free",
    upgrade_compare_features: "Compare full capabilities",
    upgrade_core_feature: "Core Feature",
    upgrade_plan_free: "Free",
    upgrade_plan_star: "Star",
    upgrade_plan_premium: "Premium",
    upgrade_plan_platinum: "Platinum",
    cmp_qr_codes: "QR Codes",
    cmp_qr_codes_sub: "Active business cards per account",
    cmp_team_members: "Team Members",
    cmp_team_members_sub: "Admins, writers, readers",
    cmp_dynamic_qr: "Dynamic QR Codes",
    cmp_dynamic_qr_sub: "Change destination URL anytime",
    cmp_custom_design: "Custom QR Design",
    cmp_custom_design_sub: "Logo, colors, shapes",
    cmp_lead_capture: "Lead Capture",
    cmp_lead_capture_sub: "Collect contacts on scan",
    cmp_analytics: "Analytics & Hot Leads",
    cmp_analytics_sub: "Scans, devices, locations",
    cmp_folders: "Folders & Organization",
    cmp_folders_sub: "Nested QR groups",
    cmp_bilingual: "Bilingual Landing (DE/EN)",
    cmp_bilingual_sub: "Auto language toggle",
    cmp_csv_export: "CSV Export",
    cmp_csv_export_sub: "Download leads and scans",
    cmp_templates: "QR Templates",
    cmp_templates_sub: "Lock fields for team consistency",
    cmp_custom_domain: "Custom Domain & White-label",
    cmp_custom_domain_sub: "Use your own URL for QR cards",
    cmp_webhook: "Lead Webhook",
    cmp_webhook_sub: "Real-time lead forwarding",
    cmp_support: "Support",
    cmp_support_sub: "Response tier",
    cmp_support_community: "Community",
    cmp_support_email: "Email",
    cmp_support_priority: "Priority",
    cmp_support_dedicated: "Dedicated",
    cmp_unlimited: "Unlimited",
    upgrade_hero_eyebrow_full: "Subscription Management",
    upgrade_hero_h: "Elevate your",
    upgrade_hero_orchestration: "orchestration",
    upgrade_hero_h_end: " experience.",
    upgrade_hero_sub: "Scale your enterprise QR infrastructure with surgical precision. Choose a tier that matches your global footprint and security requirements.",
    upgrade_current_label: "Current Plan",
    upgrade_for_individuals: "For individual experimenters.",
    upgrade_for_smb: "Perfect for small businesses.",
    upgrade_for_high_vol: "High-volume orchestration.",
    upgrade_for_enterprise: "Ultimate enterprise control.",
    upgrade_per_mo: "/mo",
    upgrade_now: "Upgrade Now",
    // Leads
    leads_title: "Leads",
    leads_subtitle: "Contacts submitted via your QR cards",
    leads_search_ph: "Search by name, email or QR card…",
    leads_all_members: "All Members",
    leads_none_search: "No leads match your search",
    leads_none: "No leads yet",
    leads_none_hint: "Enable Lead Capture on a QR card to start collecting contacts.",
    leads_count_one: "lead",
    leads_count_many: "leads",
    leads_open_live: "Open Live Card",
    leads_edit: "Edit",
    leads_analytics: "Analytics",
    leads_preview_qr: "Preview QR code",
    leads_edit_card: "Edit QR card",
    leads_qr_card: "QR Card",
    // Folders
    folders_title: "Folders",
    folders_total_suffix: "folders total",
    folders_load_error: "Failed to load",
    folders_name_ph: "Folder name",
    folders_save: "Save",
    folders_create: "Create",
    folders_move: "Move folder",
    folders_move_for: "New parent for",
    folders_root_option: "— Root (no parent folder)",
    folders_moving: "Moving...",
    folders_move_btn: "Move",
    folders_subfolder: "Subfolder",
    folders_rename: "Rename",
    folders_delete: "Delete",
    folders_delete_q: "Delete folder?",
    folders_delete_body: "will be permanently deleted.",
    folders_delete_move_title: "Contents will be moved:",
    folders_delete_move_qrs: "QR card(s) will be moved",
    folders_delete_move_users: "team member(s) will be moved",
    folders_delete_move_subfolders: "subfolder(s) will be moved",
    folders_delete_move_to_parent: "to the parent folder",
    folders_delete_move_to_root: "to the root (no folder)",
    folders_structure: "Structure",
    folders_click_to_open: "Click to open",
    folders_none: "No folders yet",
    folders_none_hint: "Folders are created automatically.",
    folders_select: "Select a folder",
    folders_select_hint: "Click on a folder on the left to view its contents.",
    folders_no_qr: "No QR codes in this folder",
    folders_assign_qr: "Assign QR codes",
    folders_yes_delete: "Yes, delete",
    folders_cancel: "Cancel",
    folders_no_name: "(no name)",
    folders_edit_title: "Edit",
    folders_open_title: "Open",
    folders_move_to_folder: "Move to folder",
    folders_remove_from: "Remove from folder",
    folders_qr_codes_label: "QR codes",
    folders_users_label: "Users",
    folders_all_qr: "All QR codes",
    folders_generic_error: "Error",
    // Clients (additional)
    clients_email: "Email",
    clients_plan: "Plan",
    clients_label: "Label",
    clients_status: "Status",
    clients_manual: "Manual",
    clients_from: "From",
    clients_to: "To",
    clients_not_found: "Client not found.",
    sign_out: "Sign out",
    signing_out: "Signing out…",
    // Public homepage
    home_signin: "Sign in",
    home_start_free: "Start for free",
    home_eyebrow: "Digital business cards made easy",
    home_hero_h1_a: "Your QR code.",
    home_hero_h1_b: "Always up to date.",
    home_hero_sub: "Create a digital business card with QR code in seconds. Contact details, logo, social media. Edit anytime, no reprint needed.",
    home_trust_no_app: "No app download",
    home_trust_free: "Start for free",
    home_trust_cancel: "Cancel anytime",
    home_card_role: "CEO · Sample Inc.",
    home_phone_company_line1: "MUSTER",
    home_phone_company_line2: "BAU GMBH",
    home_phone_name: "Max Mustermann",
    home_phone_role: "Site manager",
    home_phone_save: "Save contact",
    home_ideal_label: "Ideal for:",
    home_ideal1: "Sales & field service",
    home_ideal2: "Job site & service",
    home_ideal3: "Networking & events",
    home_features_title: `Why ${BRAND_NAME}?`,
    home_feat1_title: "Digital business cards",
    home_feat1_desc: "Create professional QR codes with contact details, logo, social media and more.",
    home_feat2_title: "Accessible everywhere",
    home_feat2_desc: "Your QR codes are available anytime, anywhere — no app download needed.",
    home_feat3_title: "Secure & reliable",
    home_feat3_desc: "Your data is stored securely and managed only by you.",
    home_how_title: "How it works",
    home_how_sub: "Your digital business card in 3 simple steps.",
    home_step1_title: "Create your QR code",
    home_step1_desc: "Add your contact details, logo and social media links. Your QR code is ready in seconds.",
    home_step2_title: "Print or share",
    home_step2_desc: "Download your QR code as a PNG and print it on business cards, flyers or wherever you like.",
    home_step3_title: "Edit anytime",
    home_step3_desc: "Change your details whenever you want. The printed QR code always points to the latest info.",
    home_demo_title: "Try it out",
    home_demo_sub: "Enter your name and see your QR code live.",
    home_demo_name: "Your name",
    home_demo_company: "Company",
    home_demo_create: "Create your own code →",
    home_use_title: "Where can you use it?",
    home_use_sub: "Anywhere you want to be found.",
    home_use1_title: "Business card",
    home_use1_desc: "Print your QR code on your business card. One scan and all your info is on the phone.",
    home_use2_title: "Flyers & posters",
    home_use2_desc: "Add your QR code to flyers, posters or brochures for instant contact.",
    home_use3_title: "Door sign / entrance",
    home_use3_desc: "Place a QR code at your entrance. Visitors save your details the moment they arrive.",
    home_pricing_title: "Simple pricing",
    home_pricing_sub: "Start for free. Upgrade when you're ready.",
    home_pricing_popular: "Most popular",
    home_pricing_per_month: "/month",
    home_pricing_no_expiry: "No expiry",
    home_cta_free: "Start for free",
    home_cta_star: "Choose Star",
    home_cta_premium: "Choose Premium",
    home_cta_platinum: "Choose Platinum",
    home_cta_select_suffix: "Choose",
    home_faq_title: "Frequently asked questions",
    home_faq_sub: "Everything you need to know, short and clear.",
    home_faq1_q: "What is a dynamic QR code?",
    home_faq1_a: "A dynamic QR code redirects to a URL you can change anytime, without replacing the printed QR code. Your customers always scan the latest info.",
    home_faq2_q: "Can I edit my QR code after printing?",
    home_faq2_a: "Yes! That's the biggest advantage of our platform. You can update name, contact details, logo, social media links and more anytime. The QR code itself stays the same.",
    home_faq3_q: "Do my customers need an app to scan?",
    home_faq3_a: "No. Every modern smartphone can scan QR codes directly with the camera app — no app download needed.",
    home_faq4_q: "How do I download my QR code?",
    home_faq4_a: "After creating it you can download your QR code as a PNG file and print it directly on business cards, flyers or your material.",
    home_faq5_q: "Can I see how often my QR code was scanned?",
    home_faq5_a: "Yes. In the dashboard you see scan stats for every QR code: when and how often it was scanned.",
    home_faq6_q: "What happens if I cancel my subscription?",
    home_faq6_a: "Your QR codes stay active. You won't be able to create new codes or use premium features until you upgrade again.",
    home_faq7_q: "Can I embed my own logo in the QR code?",
    home_faq7_a: "Yes. Starting with the Star plan you can embed your logo in the centre of the QR code for a professional, on-brand look.",
    home_footer_about: "Digital business cards with QR code. Create once, update anytime. No reprint required.",
    home_footer_platform: "Platform",
    home_footer_pricing: "Pricing",
    home_footer_faq: "FAQ",
    home_footer_start: "Start now",
    home_footer_start_desc: "Create your first QR code for free, in less than 2 minutes.",
    home_footer_register: "Register for free",
    home_footer_rights: "All rights reserved.",
    home_footer_made_in: "Made in Switzerland 🇨🇭",
    // Sidebar (additional)
    nav_leads: "Leads",
    sidebar_enterprise: "Enterprise Suite",
    sidebar_create_qr: "Create QR Code",
    // Settings - company / branding
    settings_company_info: "Company Information",
    settings_company_subtitle: "Organization details and contact info — editable by admins, usable in templates",
    settings_brand_name: "Brand name",
    settings_brand_logo: "Logo",
    settings_brand_color: "Brand color",
    settings_company_address: "Address",
    settings_company_phone: "Phone",
    settings_company_email: "Email",
    settings_company_website: "Website",
    settings_save: "Save",
    settings_saved: "Saved!",
    settings_org_name: "Organization Name",
    settings_org_name_ph: "Your organization name",
    settings_contact_info: "Contact Info",
    settings_phone_ph: "+41 00 000 00 00",
    settings_email_ph: "info@company.com",
    settings_website_ph: "www.company.com",
    settings_social_media: "Social Media",
    settings_address: "Address",
    settings_street_ph: "Street",
    settings_streetnr_ph: "No.",
    settings_plz_ph: "ZIP",
    settings_city_ph: "City",
    settings_country_ph: "Country",
    settings_save_company: "Save Company Info",
    settings_saving: "Saving…",
    settings_saved_short: "Saved",
    settings_platform_prefs: "Platform Preferences",
    settings_regional: "Regional",
    settings_language: "Language",
    settings_timezone: "Timezone",
    settings_features: "Features",
    settings_lead_capture: "Lead Capture",
    settings_lead_capture_hint: "Default for new QR codes. Existing QR codes and their captured leads stay as they are — only newly created QR codes will follow this setting.",
    // Codes page
    codes_page_title: "QR Codes",
    codes_page_subtitle: "Manage and monitor your enterprise QR infrastructure.",
    codes_recent: "Recent QR Codes",
    codes_search_label: "Search",
    codes_filter_label: "Filter",
    codes_sort_label: "Sort",
    codes_folder_label: "Folder",
    codes_folder_all: "All folders",
    codes_folder_none: "No folder",
    codes_export_folder: "Export Folder",
    codes_export_csv: "CSV Export",
    codes_back_to_codes: "QR Codes",
    codes_new_folder: "New folder",
    codes_subfolder_ph: "Subfolder name",
    codes_folder_ph: "Folder name",
    codes_create_folder_btn: "Create",
    codes_folders_section: "FOLDERS",
    codes_view_all_folders: "View all folders",
    codes_qr_singular: "QR Code",
    codes_qr_plural: "QR Codes",
    codes_pause_folder: "Pause all QRs in folder",
    codes_activate_folder: "Activate all QRs in folder",
    codes_drag_remove: "Drag here to remove from folder",
    codes_qrs_in_folder_prefix: "QR CODES IN",
    codes_recent_section: "UNCATEGORIZED",
    codes_all_members: "All Members",
    codes_created_by_team: "Created by",
    codes_delete_folder: "Delete folder",
    codes_delete_folder_title: "Delete folder",
    codes_delete_folder_subtitle: "What should happen to the QR codes inside?",
    codes_delete_folder_move: "Keep QR codes",
    codes_delete_folder_move_desc: "Move QR codes to \"Uncategorized\" and delete the folder (including any subfolders).",
    codes_delete_folder_purge: "Delete everything",
    codes_delete_folder_purge_desc: "Permanently delete the folder, all subfolders, and every QR code inside.",
    codes_delete_folder_cancel: "Cancel",
    codes_delete_all_btn: "Delete all QR codes",
    codes_delete_all_root_title: "Delete all QR codes?",
    codes_delete_all_root_body: "This will permanently delete EVERY QR code in your organization — including those inside folders and subfolders. The folders themselves will remain.",
    codes_delete_all_folder_title: "Delete all QR codes in this folder?",
    codes_delete_all_folder_body: "This will permanently delete every QR code inside this folder and any subfolders. The folders themselves will remain.",
    codes_delete_all_count: "Affected:",
    codes_delete_all_confirm: "Permanently delete",
    codes_delete_all_cancel: "Cancel",
    codes_folder_tree_close: "Close",
    codes_departed_members: "Departed members only",
    codes_departed_divider: "──────────",
    departed_badge_tooltip: "Click for history",
    departed_modal_title: "Created by departed member",
    departed_modal_subtitle: "This QR card was created by a user who left the organisation. The card remains under the admin account.",
    departed_modal_creator: "Original creator",
    departed_modal_role: "Role",
    departed_modal_card_created: "Card created",
    departed_modal_left: "Account deleted",
    departed_modal_unknown: "Unknown",
    departed_modal_close: "Close",
    // Users page
    users_team_access: "Team Access",
    users_team_subtitle: "Orchestrate your enterprise hierarchy. Control permissions, invite stakeholders, and manage organizational growth from one central hub.",
    users_export_list: "Export List",
    users_invite_member: "Invite Member",
    users_stat_total: "Total Users",
    users_stat_admins: "Admins",
    users_stat_pending: "Pending Invites",
    users_table_title: "Current Team Members",
    users_col_user: "User Details",
    users_col_access: "Access Level",
    users_col_status: "Status",
    users_col_join: "Join Date",
    users_col_actions: "Actions",
  },
};

type Translations = typeof t.de;

interface LangContextType {
  lang: Lang;
  tr: Translations;
  toggleLang: () => void;
}

const LangContext = createContext<LangContextType>({
  lang: "de",
  tr: t.de,
  toggleLang: () => {},
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("de");

  useEffect(() => {
    const stored = localStorage.getItem("dashboard_lang") as Lang | null;
    if (stored === "en" || stored === "de") setLang(stored);
  }, []);

  function toggleLang() {
    setLang((prev) => {
      const next = prev === "de" ? "en" : "de";
      localStorage.setItem("dashboard_lang", next);
      return next;
    });
  }

  return (
    <LangContext.Provider value={{ lang, tr: t[lang], toggleLang }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
